// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockconfigrpc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewLoader creates a new instance of Loader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Loader {
	mock := &Loader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

type Loader_Expecter struct {
	mock *mock.Mock
}

func (_m *Loader) EXPECT() *Loader_Expecter {
	return &Loader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type Loader
func (_mock *Loader) Load(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Loader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Loader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - v any
func (_e *Loader_Expecter) Load(v interface{}) *Loader_Load_Call {
	return &Loader_Load_Call{Call: _e.mock.On("Load", v)}
}

func (_c *Loader_Load_Call) Run(run func(v any)) *Loader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Loader_Load_Call) Return(err error) *Loader_Load_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Loader_Load_Call) RunAndReturn(run func(v any) error) *Loader_Load_Call {
	_c.Call.Return(run)
	return _c
}
