// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockconfigrpc

import (
	mock "github.com/stretchr/testify/mock"
)

// NewLoader creates a new instance of Loader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoader[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *Loader[T] {
	mock := &Loader[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Loader is an autogenerated mock type for the Loader type
type Loader[T any] struct {
	mock.Mock
}

type Loader_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *Loader[T]) EXPECT() *Loader_Expecter[T] {
	return &Loader_Expecter[T]{mock: &_m.Mock}
}

// Load provides a mock function for the type Loader
func (_mock *Loader[T]) Load() (*T, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*T, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *T); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Loader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Loader_Load_Call[T any] struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *Loader_Expecter[T]) Load() *Loader_Load_Call[T] {
	return &Loader_Load_Call[T]{Call: _e.mock.On("Load")}
}

func (_c *Loader_Load_Call[T]) Run(run func()) *Loader_Load_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Loader_Load_Call[T]) Return(v *T, err error) *Loader_Load_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Loader_Load_Call[T]) RunAndReturn(run func() (*T, error)) *Loader_Load_Call[T] {
	_c.Call.Return(run)
	return _c
}
