// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktxn

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/adapters/txn"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewDatastore creates a new instance of Datastore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatastore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Datastore {
	mock := &Datastore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Datastore is an autogenerated mock type for the Datastore type
type Datastore struct {
	mock.Mock
}

type Datastore_Expecter struct {
	mock *mock.Mock
}

func (_m *Datastore) EXPECT() *Datastore_Expecter {
	return &Datastore_Expecter{mock: &_m.Mock}
}

// CreateAuditEvent provides a mock function for the type Datastore
func (_mock *Datastore) CreateAuditEvent(context1 context.Context, auditEvent *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Datastore_CreateAuditEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditEvent'
type Datastore_CreateAuditEvent_Call struct {
	*mock.Call
}

// CreateAuditEvent is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEvent *entities.AuditEvent
func (_e *Datastore_Expecter) CreateAuditEvent(context1 interface{}, auditEvent interface{}) *Datastore_CreateAuditEvent_Call {
	return &Datastore_CreateAuditEvent_Call{Call: _e.mock.On("CreateAuditEvent", context1, auditEvent)}
}

func (_c *Datastore_CreateAuditEvent_Call) Run(run func(context1 context.Context, auditEvent *entities.AuditEvent)) *Datastore_CreateAuditEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(*entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_CreateAuditEvent_Call) Return(err error) *Datastore_CreateAuditEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Datastore_CreateAuditEvent_Call) RunAndReturn(run func(context1 context.Context, auditEvent *entities.AuditEvent) error) *Datastore_CreateAuditEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type Datastore
func (_mock *Datastore) CreateResource(context1 context.Context, resource *entities.Resource) error {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) error); ok {
		r0 = returnFunc(context1, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Datastore_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type Datastore_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *Datastore_Expecter) CreateResource(context1 interface{}, resource interface{}) *Datastore_CreateResource_Call {
	return &Datastore_CreateResource_Call{Call: _e.mock.On("CreateResource", context1, resource)}
}

func (_c *Datastore_CreateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *Datastore_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_CreateResource_Call) Return(err error) *Datastore_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Datastore_CreateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) error) *Datastore_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type Datastore
func (_mock *Datastore) DeleteResource(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Datastore_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type Datastore_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *Datastore_Expecter) DeleteResource(context1 interface{}, uUID interface{}) *Datastore_DeleteResource_Call {
	return &Datastore_DeleteResource_Call{Call: _e.mock.On("DeleteResource", context1, uUID)}
}

func (_c *Datastore_DeleteResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *Datastore_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_DeleteResource_Call) Return(err error) *Datastore_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Datastore_DeleteResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *Datastore_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type Datastore
func (_mock *Datastore) GetResource(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Datastore_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type Datastore_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *Datastore_Expecter) GetResource(context1 interface{}, uUID interface{}) *Datastore_GetResource_Call {
	return &Datastore_GetResource_Call{Call: _e.mock.On("GetResource", context1, uUID)}
}

func (_c *Datastore_GetResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *Datastore_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_GetResource_Call) Return(resource *entities.Resource, err error) *Datastore_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *Datastore_GetResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error)) *Datastore_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditEvents provides a mock function for the type Datastore
func (_mock *Datastore) ListAuditEvents(context1 context.Context) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditEvents")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Datastore_ListAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditEvents'
type Datastore_ListAuditEvents_Call struct {
	*mock.Call
}

// ListAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Datastore_Expecter) ListAuditEvents(context1 interface{}) *Datastore_ListAuditEvents_Call {
	return &Datastore_ListAuditEvents_Call{Call: _e.mock.On("ListAuditEvents", context1)}
}

func (_c *Datastore_ListAuditEvents_Call) Run(run func(context1 context.Context)) *Datastore_ListAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Datastore_ListAuditEvents_Call) Return(auditEvents []*entities.AuditEvent, err error) *Datastore_ListAuditEvents_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *Datastore_ListAuditEvents_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.AuditEvent, error)) *Datastore_ListAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type Datastore
func (_mock *Datastore) ListResources(context1 context.Context) ([]*entities.Resource, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []*entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.Resource, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.Resource); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Datastore_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type Datastore_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Datastore_Expecter) ListResources(context1 interface{}) *Datastore_ListResources_Call {
	return &Datastore_ListResources_Call{Call: _e.mock.On("ListResources", context1)}
}

func (_c *Datastore_ListResources_Call) Run(run func(context1 context.Context)) *Datastore_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Datastore_ListResources_Call) Return(resources []*entities.Resource, err error) *Datastore_ListResources_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *Datastore_ListResources_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.Resource, error)) *Datastore_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type Datastore
func (_mock *Datastore) UpdateResource(context1 context.Context, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Resource) error); ok {
		r1 = returnFunc(context1, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Datastore_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type Datastore_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *Datastore_Expecter) UpdateResource(context1 interface{}, resource interface{}) *Datastore_UpdateResource_Call {
	return &Datastore_UpdateResource_Call{Call: _e.mock.On("UpdateResource", context1, resource)}
}

func (_c *Datastore_UpdateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *Datastore_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_UpdateResource_Call) Return(resource1 *entities.Resource, err error) *Datastore_UpdateResource_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *Datastore_UpdateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) (*entities.Resource, error)) *Datastore_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAuditEvents provides a mock function for the type Datastore
func (_mock *Datastore) WatchAuditEvents(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEventCh)

	if len(ret) == 0 {
		panic("no return value specified for WatchAuditEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan<- *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEventCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Datastore_WatchAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAuditEvents'
type Datastore_WatchAuditEvents_Call struct {
	*mock.Call
}

// WatchAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEventCh chan<- *entities.AuditEvent
func (_e *Datastore_Expecter) WatchAuditEvents(context1 interface{}, auditEventCh interface{}) *Datastore_WatchAuditEvents_Call {
	return &Datastore_WatchAuditEvents_Call{Call: _e.mock.On("WatchAuditEvents", context1, auditEventCh)}
}

func (_c *Datastore_WatchAuditEvents_Call) Run(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent)) *Datastore_WatchAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(chan<- *entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Datastore_WatchAuditEvents_Call) Return(err error) *Datastore_WatchAuditEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Datastore_WatchAuditEvents_Call) RunAndReturn(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error) *Datastore_WatchAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvider creates a new instance of Provider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *Provider {
	mock := &Provider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

type Provider_Expecter struct {
	mock *mock.Mock
}

func (_m *Provider) EXPECT() *Provider_Expecter {
	return &Provider_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type Provider
func (_mock *Provider) BeginTx(context1 context.Context) (txn.Datastore, txn.CommitFn, txn.RollbackFn, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 txn.Datastore
	var r1 txn.CommitFn
	var r2 txn.RollbackFn
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (txn.Datastore, txn.CommitFn, txn.RollbackFn, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) txn.Datastore); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txn.Datastore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) txn.CommitFn); ok {
		r1 = returnFunc(context1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(txn.CommitFn)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) txn.RollbackFn); ok {
		r2 = returnFunc(context1)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(txn.RollbackFn)
		}
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context) error); ok {
		r3 = returnFunc(context1)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// Provider_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type Provider_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Provider_Expecter) BeginTx(context1 interface{}) *Provider_BeginTx_Call {
	return &Provider_BeginTx_Call{Call: _e.mock.On("BeginTx", context1)}
}

func (_c *Provider_BeginTx_Call) Run(run func(context1 context.Context)) *Provider_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Provider_BeginTx_Call) Return(datastore txn.Datastore, commitFn txn.CommitFn, rollbackFn txn.RollbackFn, err error) *Provider_BeginTx_Call {
	_c.Call.Return(datastore, commitFn, rollbackFn, err)
	return _c
}

func (_c *Provider_BeginTx_Call) RunAndReturn(run func(context1 context.Context) (txn.Datastore, txn.CommitFn, txn.RollbackFn, error)) *Provider_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Datastore provides a mock function for the type Provider
func (_mock *Provider) Datastore() txn.Datastore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Datastore")
	}

	var r0 txn.Datastore
	if returnFunc, ok := ret.Get(0).(func() txn.Datastore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txn.Datastore)
		}
	}
	return r0
}

// Provider_Datastore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Datastore'
type Provider_Datastore_Call struct {
	*mock.Call
}

// Datastore is a helper method to define mock.On call
func (_e *Provider_Expecter) Datastore() *Provider_Datastore_Call {
	return &Provider_Datastore_Call{Call: _e.mock.On("Datastore")}
}

func (_c *Provider_Datastore_Call) Run(run func()) *Provider_Datastore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Provider_Datastore_Call) Return(datastore txn.Datastore) *Provider_Datastore_Call {
	_c.Call.Return(datastore)
	return _c
}

func (_c *Provider_Datastore_Call) RunAndReturn(run func() txn.Datastore) *Provider_Datastore_Call {
	_c.Call.Return(run)
	return _c
}
