{
 "title": "ConnectRPC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(rpc.server.duration_bucket{rpc.system=\"connect_rpc\"},service.name)"
    }
   },
   {
    "name": "rpc_service",
    "label": "RPC Service",
    "query": {
     "query": "label_values(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\"},rpc.service)"
    }
   },
   {
    "name": "rpc_method",
    "label": "RPC Method",
    "query": {
     "query": "label_values(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\", rpc.service=~\"$rpc_service\"},rpc.method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Description", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "This dashboard provides visualisations for 3 of the 4 golden signals: Errors,\nLatency and Traffic.\n\nIt aims to track compliance with the following [SLOs][1]:\n\n* 99% of requests must be served within 100ms.\n* 99% of requests must result in a success response.\n\nThe following [error codes][2] are classed as internal errors included in error response calculations.\n\n- `unknown`\n- `deadline_exceeded`\n- `unimplemented`\n- `internal`\n- `unavailable`\n- `data_loss`\n\n[1]: https://sre.google/sre-book/service-level-objectives/\n[2]: https://connectrpc.com/docs/protocol#error-codes"
   }
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Above Latency Threshold",
   "type": "stat",
   "description": "The percentage of requests that exceeded the latency threshold across the current time range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",le=\"250\"}[$__rate_interval])) - sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",le=\"100\"}[$__rate_interval]))) / sum(increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "stat",
   "description": "The percentage of requests that resulted in error responses across the current time range.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) / sum(increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Above Latency Threshold",
   "type": "timeseries",
   "description": "The percentage of requests that exceeded the latency threshold.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum by(service.name,rpc.service,rpc.method) (increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",le=\"250\"}[$__rate_interval])) - sum by(service.name,rpc.service,rpc.method) (increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",le=\"100\"}[$__rate_interval]))) / sum by(service.name,rpc.service,rpc.method) (increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "{{service.name}} {{rpc.service}}/{{rpc.method}}"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "description": "The percentage of requests that resulted in error responses.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(service.name,rpc.service,rpc.method) (increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) / sum by(service.name,rpc.service,rpc.method) (increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "{{service.name}} {{rpc.service}}/{{rpc.method}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "P99 Average (Success)",
   "type": "stat",
   "description": "The P99 latency for success responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P99 Average (Error)",
   "type": "stat",
   "description": "The P99 latency for error responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P90 Average (Success)",
   "type": "stat",
   "description": "The P90 latency for success responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P90 Average (Error)",
   "type": "stat",
   "description": "The P90 latency for error responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P50 Average (Success)",
   "type": "stat",
   "description": "The P50 latency for success responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "P50 Average (Error)",
   "type": "stat",
   "description": "The P50 latency for error responses across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "timeseries",
   "description": "The latency for all responses.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Success Responses",
   "type": "timeseries",
   "description": "The latency for success responses.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code!~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "description": "the latency for error responses.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(increase(rpc.server.duration_bucket{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\",rpc.connect_rpc.error_code=~\"unknown|deadline_exceeded|unimplemented|internal|unavailable|data_loss\"}[$__rate_interval])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Error Codes",
   "type": "piechart",
   "description": "Total responses by error code for the current time range.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(rpc.connect_rpc.error_code) (increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "{{rpc.connect_rpc.error_code}}"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "timeseries",
   "description": "The number of responses.",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 33 },
   "targets": [
    {
     "expr": "sum(increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval])) default 0",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "By Error Code",
   "type": "timeseries",
   "description": "The number of responses by error code.",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 33 },
   "targets": [
    {
     "expr": "sum by(rpc.connect_rpc.error_code) (increase(rpc.server.duration_count{rpc.system=\"connect_rpc\",service.name=~\"$service_name\",rpc.service=~\"$rpc_service\",rpc.method=~\"$rpc_method\"}[$__rate_interval]))",
     "legendFormat": "{{rpc.connect_rpc.error_code}}"
    }
   ]
  }
 ]
}