---
# https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md

env:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  GF_AUTH_BASIC_ENABLED: "false"
  GF_INSTALL_PLUGINS: "victoriametrics-metrics-datasource,victoriametrics-logs-datasource"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: "VictoriaMetrics"
        type: "victoriametrics-metrics-datasource"
        uid: "victoriametrics"
        url: "http://victoria-metrics-single-server.default.svc.cluster.local:8428/"
        access: "proxy"
        basicAuth: false
        isDefault: true
        editable: false

      - name: "VictoriaLogs"
        type: "victoriametrics-logs-datasource"
        uid: "victorialogs"
        url: "http://victoria-logs-single-server.default.svc.cluster.local:9428/"
        access: "proxy"
        basicAuth: false
        isDefault: false
        editable: false

      - name: "VictoriaTraces"
        type: "jaeger"
        uid: "victoriatraces"
        url: "http://victoria-traces-single-vt-single-server.default.svc.cluster.local:10428/select/jaeger/"
        access: "proxy"
        basicAuth: false
        isDefault: false
        editable: false

      - name: "Tempo"
        type: "tempo"
        uid: "tempo"
        url: "http://tempo.default.svc.cluster.local:3200/"
        access: "proxy"
        basicAuth: false
        isDefault: false
        editable: false

dashboardProviders:
  dashboardproviders.yaml:
     apiVersion: 1
     providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards/example
          foldersFromFilesStructure: true

dashboardsConfigMaps:
  example: grafana-dashboards
