---
# https://golangci-lint.run/usage/configuration/

version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - exhaustive
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - iface
    - importas
    - intrange
    - makezero
    - mirror
    - misspell
    - mnd
    - modernize
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    gocognit:
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    goconst:
      # allow hardcoded strings in unit tests
      # or rather don't encourage tests and non-tests to share consts
      ignore-tests: true
    godot:
      exclude:
        - "^\\s*\\[.+?\\]:\\s+" # ignore markdown ref links
    mnd:
      ignored-functions:
        - "^os\\.OpenFile$"
    sloglint:
      attr-only: true
      context: all
      static-msg: true
      no-raw-keys: true
      key-naming-case: snake
      forbidden-keys:
        - time
        - level
        - msg
        - source

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - .*/mocks_test\.go$

    rules:
      - path: tools/
        linters:
          # allow less strict logging for tools
          - sloglint

      - path: .*_test\.go$
        linters:
          # allow less strict logging for examples and unit tests
          - sloglint

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gci
    - gofumpt

  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
