# https://vektra.github.io/mockery/latest/configuration/

dir: 'mocks/{{ trimPrefix .PackagePath "github.com/mattdowdell/sandbox/internal/" | dir }}/mock{{ .PackagePath | base }}'
disable-version-string: true
filename: "mock_{{ .InterfaceName | snakecase }}.go"
issue-845-fix: true
mockname: "{{ .InterfaceName }}"
outpkg: "mock{{ .PackageName }}"
resolve-type-alias: false
with-expecter: true

packages:
  github.com/mattdowdell/sandbox/internal/adapters/examplerpc:
    config:
      all: true
  github.com/mattdowdell/sandbox/internal/drivers/rpcserver:
    config:
      all: true
  github.com/mattdowdell/sandbox/internal/domain/repositories:
    config:
      all: true
