# https://docs.docker.com/reference/compose-file/

services:
  dev:
    image: "ghcr.io/mattdowdell/sandbox/example-dev:local"
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
      pull: true
    init: true
    hostname: example-dev
    volumes:
      - ".:/home/dev/ws"
    restart: always
