# https://docs.docker.com/reference/compose-file/

services:
  dev:
    image: example-dev:local
    build:
      context: .
      target: dev
    init: true
    hostname: example-dev
    volumes:
      - ".:/home/dev/ws"

  rpc:
    image: "example-rpc:local"
    build:
      context: .
      target: runtime
      args:
        SERVICE: example-rpc
    entrypoint: ["/example-rpc"]
    environment:
      APP_RPCSERVER_HOST: "0.0.0.0"
      APP_METERPROVIDER_ENDPOINT: "http://victoria-metrics:8428/opentelemetry/v1/metrics"
      APP_TRACERPROVIDER_ENDPOINT: "http://jaeger:4318"
      OTEL_GO_X_DEPRECATED_RUNTIME_METRICS: "false"
    ports:
      - "127.0.0.1:5000:5000"
    healthcheck:
      test: [ "CMD", "/example-health" ]
      start_period: "30s"
      start_interval: "1s"
    depends_on:
      jaeger:
        condition: service_healthy
      victoria-metrics:
        condition: service_healthy

  jaeger:
    image: "mirror.gcr.io/jaegertracing/jaeger:2.2.0"
    ports:
      - "127.0.0.1:16686:16686"
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:16686/" ]
      start_period: "30s"
      start_interval: "1s"

  # TODO: use plain prometheus?
  #       avoids need for grafana plugin, but modifies meter provider to enable scraping
  victoria-metrics:
    image: "mirror.gcr.io/victoriametrics/victoria-metrics:latest" # TODO: pick tag
    ports:
      - "127.0.0.1:8428:8428"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:8428/-/healthy" ]
      start_period: "30s"
      start_interval: "1s"

  grafana:
    image: "mirror.gcr.io/grafana/grafana:latest"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_BASIC_ENABLED: "false"
      # while victoria-metrics is somewhat compatible with prometheus, it differs just enough that
      # some parts are broken, see https://github.com/grafana/grafana/issues/42615
      GF_INSTALL_PLUGINS: "https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.3/victoriametrics-datasource-v0.10.3.zip;victoriametrics-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "victoriametrics-datasource"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./config/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro"
      - "./config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro"
      - "./config/dashboards:/etc/dashboards:rw"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/health" ]
      start_period: "30s"
      start_interval: "1s"


