# https://docs.docker.com/reference/compose-file/

services:
  dev:
    image: example-dev:local
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.dev
    init: true
    hostname: example-dev
    volumes:
      - ".:/home/dev/ws"
    restart: always
