# https://docs.docker.com/reference/dockerfile/
#
# mirror.gcr.io caches of popular docker hub images, but does not add rate limiting.
# See https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images.

# ------------
# Dependencies
# ------------

FROM ghcr.io/gitleaks/gitleaks:v8.30.0@sha256:691af3c7c5a48b16f187ce3446d5f194838f91238f27270ed36eef6359a574d9 AS gitleaks
FROM ghcr.io/aquasecurity/trivy:0.69.0@sha256:33f816d414b9d582d25bb737ffa4a632ae34e222f7ec1b50252cef0ce2266006 AS trivy

# -------------
# Devenv target
# -------------

FROM mirror.gcr.io/golang:1.25-bookworm@sha256:2f768d462dbffbb0f0b3a5171009f162945b086f326e0b2a8fd5d29c3219ff14 AS dev

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        postgresql-client \
        pipx \
    ;

RUN set -eux; \
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | \
    bash -s -- --to /usr/local/bin;

RUN set -eux; \
    useradd --comment Dev --create-home --user-group dev;

ENV GOPATH=''
USER dev

RUN set -eux; \
    echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> /home/dev/.bashrc; \
    pipx ensurepath; \
    mkdir -p /home/dev/ws; \
    git config --global --add safe.directory /home/dev/ws;

COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/gitleaks
COPY --from=trivy /usr/local/bin/trivy /usr/bin/trivy

ARG ZIZMOR_VERSION=1.6.0
# TODO: add cache mounts?
RUN set -eux; \
    pipx install zizmor==${ZIZMOR_VERSION};

# TODO: add cache mounts
RUN set -eux; \
    go install github.com/bwplotka/bingo@latest;

WORKDIR /home/dev/ws

CMD ["sleep", "inf"]
