# https://docs.docker.com/reference/dockerfile/
#
# mirror.gcr.io caches of popular docker hub images, but does not add rate limiting.
# See https://cloud.google.com/artifact-registry/docs/pull-cached-dockerhub-images.

# ------------
# Dependencies
# ------------

FROM ghcr.io/gitleaks/gitleaks:v8.28.0@sha256:cdbb7c955abce02001a9f6c9f602fb195b7fadc1e812065883f695d1eeaba854 AS gitleaks
FROM ghcr.io/aquasecurity/trivy:0.64.1@sha256:a8ca29078522f30393bdb34225e4c0994d38f37083be81a42da3a2a7e1488e9e AS trivy

# -------------
# Devenv target
# -------------

FROM mirror.gcr.io/golang:1.24-bookworm@sha256:69adc37c19ac6ef724b561b0dc675b27d8c719dfe848db7dd1092a7c9ac24bc6 AS dev

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,target=/var/lib/apt,sharing=locked \
    set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        postgresql-client \
        pipx \
    ;

RUN set -eux; \
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | \
    bash -s -- --to /usr/local/bin;

RUN set -eux; \
    useradd --comment Dev --create-home --user-group dev;

ENV GOPATH=''
USER dev

RUN set -eux; \
    echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> /home/dev/.bashrc; \
    pipx ensurepath; \
    mkdir -p /home/dev/ws; \
    git config --global --add safe.directory /home/dev/ws;

COPY --from=gitleaks /usr/bin/gitleaks /usr/bin/gitleaks
COPY --from=golangci-lint /usr/bin/golangci-lint /usr/bin/golangci-lint
COPY --from=trivy /usr/local/bin/trivy /usr/bin/trivy

ARG ZIZMOR_VERSION=1.6.0
# TODO: add cache mounts?
RUN set -eux; \
    pipx install zizmor==${ZIZMOR_VERSION};

# TODO: add cache mounts
RUN set -eux; \
    go install github.com/bwplotka/bingo@latest;

WORKDIR /home/dev/ws

CMD ["sleep", "inf"]
