//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/gofrs/uuid/v5"
	"time"
)

type Resources struct {
	ID        uuid.UUID `sql:"primary_key"`
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
