module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.24.0

retract (
	// module cache poisoned, use v1.10.1
	v1.10.0
	// module cache poisoned, use v1.9.1
	v1.9.0
)

require connectrpc.com/connect v1.19.1 // cmd/protoc-gen-connect-go
