// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package examplerpc

import (
	"context"
	"log/slog"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	"github.com/mattdowdell/sandbox/internal/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResourceFacade creates a new instance of MockResourceFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceFacade {
	mock := &MockResourceFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceFacade is an autogenerated mock type for the ResourceFacade type
type MockResourceFacade struct {
	mock.Mock
}

type MockResourceFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceFacade) EXPECT() *MockResourceFacade_Expecter {
	return &MockResourceFacade_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockResourceFacade
func (_mock *MockResourceFacade) Create(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceFacade_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockResourceFacade_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource *entities.Resource
func (_e *MockResourceFacade_Expecter) Create(context1 interface{}, logger interface{}, resource interface{}) *MockResourceFacade_Create_Call {
	return &MockResourceFacade_Create_Call{Call: _e.mock.On("Create", context1, logger, resource)}
}

func (_c *MockResourceFacade_Create_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource)) *MockResourceFacade_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 *entities.Resource
		if args[2] != nil {
			arg2 = args[2].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceFacade_Create_Call) Return(resource1 *entities.Resource, err error) *MockResourceFacade_Create_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *MockResourceFacade_Create_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error)) *MockResourceFacade_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockResourceFacade
func (_mock *MockResourceFacade) Delete(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) error {
	ret := _mock.Called(context1, logger, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) error); ok {
		r0 = returnFunc(context1, logger, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResourceFacade_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockResourceFacade_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - uUID uuid.UUID
func (_e *MockResourceFacade_Expecter) Delete(context1 interface{}, logger interface{}, uUID interface{}) *MockResourceFacade_Delete_Call {
	return &MockResourceFacade_Delete_Call{Call: _e.mock.On("Delete", context1, logger, uUID)}
}

func (_c *MockResourceFacade_Delete_Call) Run(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID)) *MockResourceFacade_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceFacade_Delete_Call) Return(err error) *MockResourceFacade_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResourceFacade_Delete_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) error) *MockResourceFacade_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockResourceFacade
func (_mock *MockResourceFacade) Get(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, uuid.UUID) error); ok {
		r1 = returnFunc(context1, logger, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceFacade_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockResourceFacade_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - uUID uuid.UUID
func (_e *MockResourceFacade_Expecter) Get(context1 interface{}, logger interface{}, uUID interface{}) *MockResourceFacade_Get_Call {
	return &MockResourceFacade_Get_Call{Call: _e.mock.On("Get", context1, logger, uUID)}
}

func (_c *MockResourceFacade_Get_Call) Run(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID)) *MockResourceFacade_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceFacade_Get_Call) Return(resource *entities.Resource, err error) *MockResourceFacade_Get_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockResourceFacade_Get_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) (*entities.Resource, error)) *MockResourceFacade_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockResourceFacade
func (_mock *MockResourceFacade) List(context1 context.Context, logger *slog.Logger, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error) {
	ret := _mock.Called(context1, logger, pager)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *repositories.Paged[*entities.Resource]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Pager) (*repositories.Paged[*entities.Resource], error)); ok {
		return returnFunc(context1, logger, pager)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Pager) *repositories.Paged[*entities.Resource]); ok {
		r0 = returnFunc(context1, logger, pager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.Paged[*entities.Resource])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Pager) error); ok {
		r1 = returnFunc(context1, logger, pager)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockResourceFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - pager repositories.Pager
func (_e *MockResourceFacade_Expecter) List(context1 interface{}, logger interface{}, pager interface{}) *MockResourceFacade_List_Call {
	return &MockResourceFacade_List_Call{Call: _e.mock.On("List", context1, logger, pager)}
}

func (_c *MockResourceFacade_List_Call) Run(run func(context1 context.Context, logger *slog.Logger, pager repositories.Pager)) *MockResourceFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Pager
		if args[2] != nil {
			arg2 = args[2].(repositories.Pager)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceFacade_List_Call) Return(paged *repositories.Paged[*entities.Resource], err error) *MockResourceFacade_List_Call {
	_c.Call.Return(paged, err)
	return _c
}

func (_c *MockResourceFacade_List_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error)) *MockResourceFacade_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockResourceFacade
func (_mock *MockResourceFacade) Update(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceFacade_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockResourceFacade_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource *entities.Resource
func (_e *MockResourceFacade_Expecter) Update(context1 interface{}, logger interface{}, resource interface{}) *MockResourceFacade_Update_Call {
	return &MockResourceFacade_Update_Call{Call: _e.mock.On("Update", context1, logger, resource)}
}

func (_c *MockResourceFacade_Update_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource)) *MockResourceFacade_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 *entities.Resource
		if args[2] != nil {
			arg2 = args[2].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResourceFacade_Update_Call) Return(resource1 *entities.Resource, err error) *MockResourceFacade_Update_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *MockResourceFacade_Update_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error)) *MockResourceFacade_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditEventFacade creates a new instance of MockAuditEventFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEventFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEventFacade {
	mock := &MockAuditEventFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditEventFacade is an autogenerated mock type for the AuditEventFacade type
type MockAuditEventFacade struct {
	mock.Mock
}

type MockAuditEventFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditEventFacade) EXPECT() *MockAuditEventFacade_Expecter {
	return &MockAuditEventFacade_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockAuditEventFacade
func (_mock *MockAuditEventFacade) List(context1 context.Context, logger *slog.Logger) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1, logger)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger) error); ok {
		r1 = returnFunc(context1, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditEventFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockAuditEventFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
func (_e *MockAuditEventFacade_Expecter) List(context1 interface{}, logger interface{}) *MockAuditEventFacade_List_Call {
	return &MockAuditEventFacade_List_Call{Call: _e.mock.On("List", context1, logger)}
}

func (_c *MockAuditEventFacade_List_Call) Run(run func(context1 context.Context, logger *slog.Logger)) *MockAuditEventFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditEventFacade_List_Call) Return(auditEvents []*entities.AuditEvent, err error) *MockAuditEventFacade_List_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *MockAuditEventFacade_List_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger) ([]*entities.AuditEvent, error)) *MockAuditEventFacade_List_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type MockAuditEventFacade
func (_mock *MockAuditEventFacade) Watch(context1 context.Context, logger *slog.Logger) <-chan *entities.AuditEvent {
	ret := _mock.Called(context1, logger)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan *entities.AuditEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) <-chan *entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.AuditEvent)
		}
	}
	return r0
}

// MockAuditEventFacade_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type MockAuditEventFacade_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
func (_e *MockAuditEventFacade_Expecter) Watch(context1 interface{}, logger interface{}) *MockAuditEventFacade_Watch_Call {
	return &MockAuditEventFacade_Watch_Call{Call: _e.mock.On("Watch", context1, logger)}
}

func (_c *MockAuditEventFacade_Watch_Call) Run(run func(context1 context.Context, logger *slog.Logger)) *MockAuditEventFacade_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditEventFacade_Watch_Call) Return(auditEventCh <-chan *entities.AuditEvent) *MockAuditEventFacade_Watch_Call {
	_c.Call.Return(auditEventCh)
	return _c
}

func (_c *MockAuditEventFacade_Watch_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger) <-chan *entities.AuditEvent) *MockAuditEventFacade_Watch_Call {
	_c.Call.Return(run)
	return _c
}
