name: Zizmor
description: Static analysis for GitHub Actions.

inputs:
  inputs:
    description: The inputs to audit.
    required: true
  persona:
    description: The persona to use while auditing.
    default: regular
    required: false
  # offline:
  #   description: Perform only offline operations.
  #   default: ""
  #   required: false
  github_token:
    description: The GitHub API token to use.
    default: ${{ github.token }}
    required: false
  github_hostname:
    description: The GitHub Server Hostname.
    default: ${{ github.server_url }}
    required: false
  no_online_audits:
    description: Perform only offline audits.
    default: "false"
    required: false
  format:
    description: The output format to emit.
    default: plain
    required: false
  # config:
  #   description: |
  #     The configuration file to load. By default, any config will be discovered
  #     relative to $CWD.
  #   default: ""
  #   required: false
  # no_config:
  #   description: Disable all configuration loading.
  #   default: ""
  #   required: false
  # no_exit_codes:
  #   description: Disable all error codes besides success and tool failure.
  #   default: ""
  #   required: false
  min_severity:
    description: Filter all results below this severity
    default: 'unknown'
    required: false
  min_confidence:
    description: Filter all results below this confidence
    default: 'unknown'
    required: false
  # cache_dir:
  #   description: |
  #     The directory to use for HTTP caching. By default, a host-appropriate
  #     user-caching directory will be used.
  #   default: ""
  #   required: false
  collect:
    description: Control which kinds of inputs are collected for auditing.
    default: 'all'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--persona=${{ inputs.persona }}"
    - "--format=${{ inputs.format }}"
    - "--min-severity=${{ inputs.min_severity }}"
    - "--min-confidence=${{ inputs.min_confidence }}"
    - "--collect=${{ inputs.collect }}"
  env:
    GH_TOKEN: ${{ inputs.github_token }}
    GH_HOSTNAME: ${{ inputs.github_hostname }}
    ZIZMOR_NO_ONLINE_AUDITS: ${{ inputs.no_online_audits }}
