// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authnrpc

import (
	"github.com/golang-jwt/jwt/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(s string) (jwt.Claims, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 jwt.Claims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (jwt.Claims, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) jwt.Claims); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jwt.Claims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - s string
func (_e *MockParser_Expecter) Parse(s interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", s)}
}

func (_c *MockParser_Parse_Call) Run(run func(s string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(claims jwt.Claims, err error) *MockParser_Parse_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(s string) (jwt.Claims, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIssuer creates a new instance of MockIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIssuer {
	mock := &MockIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIssuer is an autogenerated mock type for the Issuer type
type MockIssuer struct {
	mock.Mock
}

type MockIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIssuer) EXPECT() *MockIssuer_Expecter {
	return &MockIssuer_Expecter{mock: &_m.Mock}
}

// Issue provides a mock function for the type MockIssuer
func (_mock *MockIssuer) Issue(s string, v uint32) (string, error) {
	ret := _mock.Called(s, v)

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, uint32) (string, error)); ok {
		return returnFunc(s, v)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint32) string); ok {
		r0 = returnFunc(s, v)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint32) error); ok {
		r1 = returnFunc(s, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIssuer_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockIssuer_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - s string
//   - v uint32
func (_e *MockIssuer_Expecter) Issue(s interface{}, v interface{}) *MockIssuer_Issue_Call {
	return &MockIssuer_Issue_Call{Call: _e.mock.On("Issue", s, v)}
}

func (_c *MockIssuer_Issue_Call) Run(run func(s string, v uint32)) *MockIssuer_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint32
		if args[1] != nil {
			arg1 = args[1].(uint32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIssuer_Issue_Call) Return(s1 string, err error) *MockIssuer_Issue_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockIssuer_Issue_Call) RunAndReturn(run func(s string, v uint32) (string, error)) *MockIssuer_Issue_Call {
	_c.Call.Return(run)
	return _c
}
