// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockconnect

import (
	"net/http"

	"connectrpc.com/connect"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStreamingHandlerConn creates a new instance of MockStreamingHandlerConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamingHandlerConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamingHandlerConn {
	mock := &MockStreamingHandlerConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamingHandlerConn is an autogenerated mock type for the StreamingHandlerConn type
type MockStreamingHandlerConn struct {
	mock.Mock
}

type MockStreamingHandlerConn_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamingHandlerConn) EXPECT() *MockStreamingHandlerConn_Expecter {
	return &MockStreamingHandlerConn_Expecter{mock: &_m.Mock}
}

// Peer provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) Peer() connect.Peer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Peer")
	}

	var r0 connect.Peer
	if returnFunc, ok := ret.Get(0).(func() connect.Peer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connect.Peer)
	}
	return r0
}

// MockStreamingHandlerConn_Peer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peer'
type MockStreamingHandlerConn_Peer_Call struct {
	*mock.Call
}

// Peer is a helper method to define mock.On call
func (_e *MockStreamingHandlerConn_Expecter) Peer() *MockStreamingHandlerConn_Peer_Call {
	return &MockStreamingHandlerConn_Peer_Call{Call: _e.mock.On("Peer")}
}

func (_c *MockStreamingHandlerConn_Peer_Call) Run(run func()) *MockStreamingHandlerConn_Peer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingHandlerConn_Peer_Call) Return(peer connect.Peer) *MockStreamingHandlerConn_Peer_Call {
	_c.Call.Return(peer)
	return _c
}

func (_c *MockStreamingHandlerConn_Peer_Call) RunAndReturn(run func() connect.Peer) *MockStreamingHandlerConn_Peer_Call {
	_c.Call.Return(run)
	return _c
}

// Receive provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) Receive(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Receive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingHandlerConn_Receive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Receive'
type MockStreamingHandlerConn_Receive_Call struct {
	*mock.Call
}

// Receive is a helper method to define mock.On call
//   - v any
func (_e *MockStreamingHandlerConn_Expecter) Receive(v interface{}) *MockStreamingHandlerConn_Receive_Call {
	return &MockStreamingHandlerConn_Receive_Call{Call: _e.mock.On("Receive", v)}
}

func (_c *MockStreamingHandlerConn_Receive_Call) Run(run func(v any)) *MockStreamingHandlerConn_Receive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamingHandlerConn_Receive_Call) Return(err error) *MockStreamingHandlerConn_Receive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingHandlerConn_Receive_Call) RunAndReturn(run func(v any) error) *MockStreamingHandlerConn_Receive_Call {
	_c.Call.Return(run)
	return _c
}

// RequestHeader provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) RequestHeader() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequestHeader")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockStreamingHandlerConn_RequestHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestHeader'
type MockStreamingHandlerConn_RequestHeader_Call struct {
	*mock.Call
}

// RequestHeader is a helper method to define mock.On call
func (_e *MockStreamingHandlerConn_Expecter) RequestHeader() *MockStreamingHandlerConn_RequestHeader_Call {
	return &MockStreamingHandlerConn_RequestHeader_Call{Call: _e.mock.On("RequestHeader")}
}

func (_c *MockStreamingHandlerConn_RequestHeader_Call) Run(run func()) *MockStreamingHandlerConn_RequestHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingHandlerConn_RequestHeader_Call) Return(header http.Header) *MockStreamingHandlerConn_RequestHeader_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockStreamingHandlerConn_RequestHeader_Call) RunAndReturn(run func() http.Header) *MockStreamingHandlerConn_RequestHeader_Call {
	_c.Call.Return(run)
	return _c
}

// ResponseHeader provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) ResponseHeader() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResponseHeader")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockStreamingHandlerConn_ResponseHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResponseHeader'
type MockStreamingHandlerConn_ResponseHeader_Call struct {
	*mock.Call
}

// ResponseHeader is a helper method to define mock.On call
func (_e *MockStreamingHandlerConn_Expecter) ResponseHeader() *MockStreamingHandlerConn_ResponseHeader_Call {
	return &MockStreamingHandlerConn_ResponseHeader_Call{Call: _e.mock.On("ResponseHeader")}
}

func (_c *MockStreamingHandlerConn_ResponseHeader_Call) Run(run func()) *MockStreamingHandlerConn_ResponseHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingHandlerConn_ResponseHeader_Call) Return(header http.Header) *MockStreamingHandlerConn_ResponseHeader_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockStreamingHandlerConn_ResponseHeader_Call) RunAndReturn(run func() http.Header) *MockStreamingHandlerConn_ResponseHeader_Call {
	_c.Call.Return(run)
	return _c
}

// ResponseTrailer provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) ResponseTrailer() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResponseTrailer")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockStreamingHandlerConn_ResponseTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResponseTrailer'
type MockStreamingHandlerConn_ResponseTrailer_Call struct {
	*mock.Call
}

// ResponseTrailer is a helper method to define mock.On call
func (_e *MockStreamingHandlerConn_Expecter) ResponseTrailer() *MockStreamingHandlerConn_ResponseTrailer_Call {
	return &MockStreamingHandlerConn_ResponseTrailer_Call{Call: _e.mock.On("ResponseTrailer")}
}

func (_c *MockStreamingHandlerConn_ResponseTrailer_Call) Run(run func()) *MockStreamingHandlerConn_ResponseTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingHandlerConn_ResponseTrailer_Call) Return(header http.Header) *MockStreamingHandlerConn_ResponseTrailer_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockStreamingHandlerConn_ResponseTrailer_Call) RunAndReturn(run func() http.Header) *MockStreamingHandlerConn_ResponseTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) Send(v any) error {
	ret := _mock.Called(v)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingHandlerConn_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockStreamingHandlerConn_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - v any
func (_e *MockStreamingHandlerConn_Expecter) Send(v interface{}) *MockStreamingHandlerConn_Send_Call {
	return &MockStreamingHandlerConn_Send_Call{Call: _e.mock.On("Send", v)}
}

func (_c *MockStreamingHandlerConn_Send_Call) Run(run func(v any)) *MockStreamingHandlerConn_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamingHandlerConn_Send_Call) Return(err error) *MockStreamingHandlerConn_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingHandlerConn_Send_Call) RunAndReturn(run func(v any) error) *MockStreamingHandlerConn_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function for the type MockStreamingHandlerConn
func (_mock *MockStreamingHandlerConn) Spec() connect.Spec {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 connect.Spec
	if returnFunc, ok := ret.Get(0).(func() connect.Spec); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connect.Spec)
	}
	return r0
}

// MockStreamingHandlerConn_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockStreamingHandlerConn_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
func (_e *MockStreamingHandlerConn_Expecter) Spec() *MockStreamingHandlerConn_Spec_Call {
	return &MockStreamingHandlerConn_Spec_Call{Call: _e.mock.On("Spec")}
}

func (_c *MockStreamingHandlerConn_Spec_Call) Run(run func()) *MockStreamingHandlerConn_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingHandlerConn_Spec_Call) Return(spec connect.Spec) *MockStreamingHandlerConn_Spec_Call {
	_c.Call.Return(spec)
	return _c
}

func (_c *MockStreamingHandlerConn_Spec_Call) RunAndReturn(run func() connect.Spec) *MockStreamingHandlerConn_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAnyRequest creates a new instance of MockAnyRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnyRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnyRequest {
	mock := &MockAnyRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnyRequest is an autogenerated mock type for the AnyRequest type
type MockAnyRequest struct {
	mock.Mock
}

type MockAnyRequest_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnyRequest) EXPECT() *MockAnyRequest_Expecter {
	return &MockAnyRequest_Expecter{mock: &_m.Mock}
}

// Any provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) Any() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Any")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockAnyRequest_Any_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Any'
type MockAnyRequest_Any_Call struct {
	*mock.Call
}

// Any is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) Any() *MockAnyRequest_Any_Call {
	return &MockAnyRequest_Any_Call{Call: _e.mock.On("Any")}
}

func (_c *MockAnyRequest_Any_Call) Run(run func()) *MockAnyRequest_Any_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_Any_Call) Return(v any) *MockAnyRequest_Any_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockAnyRequest_Any_Call) RunAndReturn(run func() any) *MockAnyRequest_Any_Call {
	_c.Call.Return(run)
	return _c
}

// HTTPMethod provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) HTTPMethod() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HTTPMethod")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAnyRequest_HTTPMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HTTPMethod'
type MockAnyRequest_HTTPMethod_Call struct {
	*mock.Call
}

// HTTPMethod is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) HTTPMethod() *MockAnyRequest_HTTPMethod_Call {
	return &MockAnyRequest_HTTPMethod_Call{Call: _e.mock.On("HTTPMethod")}
}

func (_c *MockAnyRequest_HTTPMethod_Call) Run(run func()) *MockAnyRequest_HTTPMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_HTTPMethod_Call) Return(s string) *MockAnyRequest_HTTPMethod_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAnyRequest_HTTPMethod_Call) RunAndReturn(run func() string) *MockAnyRequest_HTTPMethod_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) Header() http.Header {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 http.Header
	if returnFunc, ok := ret.Get(0).(func() http.Header); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}
	return r0
}

// MockAnyRequest_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockAnyRequest_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) Header() *MockAnyRequest_Header_Call {
	return &MockAnyRequest_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockAnyRequest_Header_Call) Run(run func()) *MockAnyRequest_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_Header_Call) Return(header http.Header) *MockAnyRequest_Header_Call {
	_c.Call.Return(header)
	return _c
}

func (_c *MockAnyRequest_Header_Call) RunAndReturn(run func() http.Header) *MockAnyRequest_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Peer provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) Peer() connect.Peer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Peer")
	}

	var r0 connect.Peer
	if returnFunc, ok := ret.Get(0).(func() connect.Peer); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connect.Peer)
	}
	return r0
}

// MockAnyRequest_Peer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peer'
type MockAnyRequest_Peer_Call struct {
	*mock.Call
}

// Peer is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) Peer() *MockAnyRequest_Peer_Call {
	return &MockAnyRequest_Peer_Call{Call: _e.mock.On("Peer")}
}

func (_c *MockAnyRequest_Peer_Call) Run(run func()) *MockAnyRequest_Peer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_Peer_Call) Return(peer connect.Peer) *MockAnyRequest_Peer_Call {
	_c.Call.Return(peer)
	return _c
}

func (_c *MockAnyRequest_Peer_Call) RunAndReturn(run func() connect.Peer) *MockAnyRequest_Peer_Call {
	_c.Call.Return(run)
	return _c
}

// Spec provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) Spec() connect.Spec {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Spec")
	}

	var r0 connect.Spec
	if returnFunc, ok := ret.Get(0).(func() connect.Spec); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(connect.Spec)
	}
	return r0
}

// MockAnyRequest_Spec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spec'
type MockAnyRequest_Spec_Call struct {
	*mock.Call
}

// Spec is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) Spec() *MockAnyRequest_Spec_Call {
	return &MockAnyRequest_Spec_Call{Call: _e.mock.On("Spec")}
}

func (_c *MockAnyRequest_Spec_Call) Run(run func()) *MockAnyRequest_Spec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_Spec_Call) Return(spec connect.Spec) *MockAnyRequest_Spec_Call {
	_c.Call.Return(spec)
	return _c
}

func (_c *MockAnyRequest_Spec_Call) RunAndReturn(run func() connect.Spec) *MockAnyRequest_Spec_Call {
	_c.Call.Return(run)
	return _c
}

// internalOnly provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) internalOnly() {
	_mock.Called()
	return
}

// MockAnyRequest_internalOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'internalOnly'
type MockAnyRequest_internalOnly_Call struct {
	*mock.Call
}

// internalOnly is a helper method to define mock.On call
func (_e *MockAnyRequest_Expecter) internalOnly() *MockAnyRequest_internalOnly_Call {
	return &MockAnyRequest_internalOnly_Call{Call: _e.mock.On("internalOnly")}
}

func (_c *MockAnyRequest_internalOnly_Call) Run(run func()) *MockAnyRequest_internalOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnyRequest_internalOnly_Call) Return() *MockAnyRequest_internalOnly_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnyRequest_internalOnly_Call) RunAndReturn(run func()) *MockAnyRequest_internalOnly_Call {
	_c.Run(run)
	return _c
}

// setRequestMethod provides a mock function for the type MockAnyRequest
func (_mock *MockAnyRequest) setRequestMethod(s string) {
	_mock.Called(s)
	return
}

// MockAnyRequest_setRequestMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setRequestMethod'
type MockAnyRequest_setRequestMethod_Call struct {
	*mock.Call
}

// setRequestMethod is a helper method to define mock.On call
//   - s string
func (_e *MockAnyRequest_Expecter) setRequestMethod(s interface{}) *MockAnyRequest_setRequestMethod_Call {
	return &MockAnyRequest_setRequestMethod_Call{Call: _e.mock.On("setRequestMethod", s)}
}

func (_c *MockAnyRequest_setRequestMethod_Call) Run(run func(s string)) *MockAnyRequest_setRequestMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAnyRequest_setRequestMethod_Call) Return() *MockAnyRequest_setRequestMethod_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAnyRequest_setRequestMethod_Call) RunAndReturn(run func(s string)) *MockAnyRequest_setRequestMethod_Call {
	_c.Run(run)
	return _c
}
