// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockusecasefacades

import (
	"context"
	"log/slog"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	"github.com/mattdowdell/sandbox/internal/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewResourceCreator creates a new instance of ResourceCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceCreator {
	mock := &ResourceCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceCreator is an autogenerated mock type for the ResourceCreator type
type ResourceCreator struct {
	mock.Mock
}

type ResourceCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceCreator) EXPECT() *ResourceCreator_Expecter {
	return &ResourceCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ResourceCreator
func (_mock *ResourceCreator) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, resource1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, resource1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, resource1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource, resource1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - resource1 *entities.Resource
func (_e *ResourceCreator_Expecter) Execute(context1 interface{}, logger interface{}, resource interface{}, resource1 interface{}) *ResourceCreator_Execute_Call {
	return &ResourceCreator_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, resource1)}
}

func (_c *ResourceCreator_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource)) *ResourceCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 *entities.Resource
		if args[3] != nil {
			arg3 = args[3].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceCreator_Execute_Call) Return(resource2 *entities.Resource, err error) *ResourceCreator_Execute_Call {
	_c.Call.Return(resource2, err)
	return _c
}

func (_c *ResourceCreator_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error)) *ResourceCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceGetter creates a new instance of ResourceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceGetter {
	mock := &ResourceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceGetter is an autogenerated mock type for the ResourceGetter type
type ResourceGetter struct {
	mock.Mock
}

type ResourceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceGetter) EXPECT() *ResourceGetter_Expecter {
	return &ResourceGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ResourceGetter
func (_mock *ResourceGetter) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) error); ok {
		r1 = returnFunc(context1, logger, resource, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - uUID uuid.UUID
func (_e *ResourceGetter_Expecter) Execute(context1 interface{}, logger interface{}, resource interface{}, uUID interface{}) *ResourceGetter_Execute_Call {
	return &ResourceGetter_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, uUID)}
}

func (_c *ResourceGetter_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID)) *ResourceGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceGetter_Execute_Call) Return(resource1 *entities.Resource, err error) *ResourceGetter_Execute_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *ResourceGetter_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) (*entities.Resource, error)) *ResourceGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceLister creates a new instance of ResourceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceLister {
	mock := &ResourceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceLister is an autogenerated mock type for the ResourceLister type
type ResourceLister struct {
	mock.Mock
}

type ResourceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceLister) EXPECT() *ResourceLister_Expecter {
	return &ResourceLister_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ResourceLister
func (_mock *ResourceLister) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource) ([]*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource) ([]*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource) []*entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceLister_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceLister_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
func (_e *ResourceLister_Expecter) Execute(context1 interface{}, logger interface{}, resource interface{}) *ResourceLister_Execute_Call {
	return &ResourceLister_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource)}
}

func (_c *ResourceLister_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource)) *ResourceLister_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceLister_Execute_Call) Return(resources []*entities.Resource, err error) *ResourceLister_Execute_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *ResourceLister_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource) ([]*entities.Resource, error)) *ResourceLister_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceUpdater creates a new instance of ResourceUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceUpdater {
	mock := &ResourceUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceUpdater is an autogenerated mock type for the ResourceUpdater type
type ResourceUpdater struct {
	mock.Mock
}

type ResourceUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceUpdater) EXPECT() *ResourceUpdater_Expecter {
	return &ResourceUpdater_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ResourceUpdater
func (_mock *ResourceUpdater) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, resource1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, resource1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, resource1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource, resource1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceUpdater_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceUpdater_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - resource1 *entities.Resource
func (_e *ResourceUpdater_Expecter) Execute(context1 interface{}, logger interface{}, resource interface{}, resource1 interface{}) *ResourceUpdater_Execute_Call {
	return &ResourceUpdater_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, resource1)}
}

func (_c *ResourceUpdater_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource)) *ResourceUpdater_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 *entities.Resource
		if args[3] != nil {
			arg3 = args[3].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceUpdater_Execute_Call) Return(resource2 *entities.Resource, err error) *ResourceUpdater_Execute_Call {
	_c.Call.Return(resource2, err)
	return _c
}

func (_c *ResourceUpdater_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error)) *ResourceUpdater_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceDeleter creates a new instance of ResourceDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceDeleter {
	mock := &ResourceDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceDeleter is an autogenerated mock type for the ResourceDeleter type
type ResourceDeleter struct {
	mock.Mock
}

type ResourceDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceDeleter) EXPECT() *ResourceDeleter_Expecter {
	return &ResourceDeleter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type ResourceDeleter
func (_mock *ResourceDeleter) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) error {
	ret := _mock.Called(context1, logger, resource, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) error); ok {
		r0 = returnFunc(context1, logger, resource, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceDeleter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceDeleter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - uUID uuid.UUID
func (_e *ResourceDeleter_Expecter) Execute(context1 interface{}, logger interface{}, resource interface{}, uUID interface{}) *ResourceDeleter_Execute_Call {
	return &ResourceDeleter_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, uUID)}
}

func (_c *ResourceDeleter_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID)) *ResourceDeleter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *ResourceDeleter_Execute_Call) Return(err error) *ResourceDeleter_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceDeleter_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) error) *ResourceDeleter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventLister creates a new instance of AuditEventLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventLister {
	mock := &AuditEventLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditEventLister is an autogenerated mock type for the AuditEventLister type
type AuditEventLister struct {
	mock.Mock
}

type AuditEventLister_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventLister) EXPECT() *AuditEventLister_Expecter {
	return &AuditEventLister_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type AuditEventLister
func (_mock *AuditEventLister) Execute(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1, logger, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1, logger, auditEvent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger, auditEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.AuditEvent) error); ok {
		r1 = returnFunc(context1, logger, auditEvent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuditEventLister_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AuditEventLister_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - auditEvent repositories.AuditEvent
func (_e *AuditEventLister_Expecter) Execute(context1 interface{}, logger interface{}, auditEvent interface{}) *AuditEventLister_Execute_Call {
	return &AuditEventLister_Execute_Call{Call: _e.mock.On("Execute", context1, logger, auditEvent)}
}

func (_c *AuditEventLister_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent)) *AuditEventLister_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.AuditEvent
		if args[2] != nil {
			arg2 = args[2].(repositories.AuditEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuditEventLister_Execute_Call) Return(auditEvents []*entities.AuditEvent, err error) *AuditEventLister_Execute_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *AuditEventLister_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) ([]*entities.AuditEvent, error)) *AuditEventLister_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventWatcher creates a new instance of AuditEventWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventWatcher {
	mock := &AuditEventWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditEventWatcher is an autogenerated mock type for the AuditEventWatcher type
type AuditEventWatcher struct {
	mock.Mock
}

type AuditEventWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventWatcher) EXPECT() *AuditEventWatcher_Expecter {
	return &AuditEventWatcher_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type AuditEventWatcher
func (_mock *AuditEventWatcher) Execute(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) <-chan *entities.AuditEvent {
	ret := _mock.Called(context1, logger, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan *entities.AuditEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) <-chan *entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger, auditEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.AuditEvent)
		}
	}
	return r0
}

// AuditEventWatcher_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AuditEventWatcher_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - auditEvent repositories.AuditEvent
func (_e *AuditEventWatcher_Expecter) Execute(context1 interface{}, logger interface{}, auditEvent interface{}) *AuditEventWatcher_Execute_Call {
	return &AuditEventWatcher_Execute_Call{Call: _e.mock.On("Execute", context1, logger, auditEvent)}
}

func (_c *AuditEventWatcher_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent)) *AuditEventWatcher_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.AuditEvent
		if args[2] != nil {
			arg2 = args[2].(repositories.AuditEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuditEventWatcher_Execute_Call) Return(auditEventCh <-chan *entities.AuditEvent) *AuditEventWatcher_Execute_Call {
	_c.Call.Return(auditEventCh)
	return _c
}

func (_c *AuditEventWatcher_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) <-chan *entities.AuditEvent) *AuditEventWatcher_Execute_Call {
	_c.Call.Return(run)
	return _c
}
