// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/mattdowdell/sandbox/internal/adapters/datastore"
	"github.com/mattdowdell/sandbox/internal/adapters/examplerpc"
	"github.com/mattdowdell/sandbox/internal/adapters/healthrpc"
	"github.com/mattdowdell/sandbox/internal/adapters/reflectrpc"
	"github.com/mattdowdell/sandbox/internal/adapters/usecasefacades"
	"github.com/mattdowdell/sandbox/internal/drivers/clock"
	"github.com/mattdowdell/sandbox/internal/drivers/config"
	"github.com/mattdowdell/sandbox/internal/drivers/config/flagoptions"
	"github.com/mattdowdell/sandbox/internal/drivers/logging"
	"github.com/mattdowdell/sandbox/internal/drivers/otelx"
	"github.com/mattdowdell/sandbox/internal/drivers/pgsql"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/otelconnectx"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/validatex"
	"github.com/mattdowdell/sandbox/internal/drivers/uuidgen"
	"github.com/mattdowdell/sandbox/internal/usecases"
)

// Injectors from wire.go:

func ProvideApp(ctx context.Context) (*App, error) {
	options := flagoptions.New()
	configConfig := config.New(options)
	mainConfig, err := LoadConfig(configConfig)
	if err != nil {
		return nil, err
	}
	appConfig := mainConfig.App
	loggingConfig := mainConfig.Logging
	v := loggerOptions()
	logger := logging.NewAsDefaultFromConfig(loggingConfig, v...)
	rpcserverConfig := mainConfig.RPCServer
	pgsqlConfig := mainConfig.Database
	db, err := pgsql.NewFromConfig(ctx, pgsqlConfig)
	if err != nil {
		return nil, err
	}
	provider := datastore.NewProvider(db)
	clockClock := clock.New()
	generator := uuidgen.New()
	createResource := usecases.NewCreateResource(clockClock, generator)
	getResource := usecases.NewGetResource()
	listResources := usecases.NewListResources()
	updateResource := usecases.NewUpdateResource(clockClock)
	deleteResource := usecases.NewDeleteResource()
	resource := usecasefacades.NewResource(provider, createResource, getResource, listResources, updateResource, deleteResource)
	listAuditEvents := usecases.NewListAuditEvents()
	watchAuditEvents := usecases.NewWatchAuditEvents()
	auditEvent := usecasefacades.NewAuditEvent(provider, listAuditEvents, watchAuditEvents)
	handler := examplerpc.New(resource, auditEvent)
	reflectrpcHandler := reflectrpc.New()
	healthrpcHandler := healthrpc.New()
	v2 := collectHandlers(handler, reflectrpcHandler, healthrpcHandler)
	v3, err := validatex.New()
	if err != nil {
		return nil, err
	}
	otelconnectxConfig := mainConfig.OtelConnect
	v4, err := otelconnectx.NewFromConfig(otelconnectxConfig)
	if err != nil {
		return nil, err
	}
	v5 := collectInterceptors(v3, v4)
	recoverer, err := rpcserver.NewRecoverer()
	if err != nil {
		return nil, err
	}
	v6 := collectHandlerOptions(v5, recoverer)
	server := rpcserver.NewFromConfig(rpcserverConfig, v2, v6)
	tracerProviderConfig := mainConfig.Tracer
	tracerProviderShutdown, err := otelx.NewTracerProviderFromConfig(ctx, tracerProviderConfig)
	if err != nil {
		return nil, err
	}
	meterProviderConfig := mainConfig.Meter
	meterProviderShutdown, err := otelx.NewMeterProviderFromConfig(ctx, meterProviderConfig)
	if err != nil {
		return nil, err
	}
	app := NewApp(appConfig, logger, server, tracerProviderShutdown, meterProviderShutdown)
	return app, nil
}
