// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/adapters/authnrpc"
	"github.com/mattdowdell/sandbox/internal/adapters/datastore"
	"github.com/mattdowdell/sandbox/internal/adapters/examplerpc"
	"github.com/mattdowdell/sandbox/internal/adapters/healthrpc"
	"github.com/mattdowdell/sandbox/internal/adapters/reflectrpc"
	"github.com/mattdowdell/sandbox/internal/adapters/usecasefacades"
	"github.com/mattdowdell/sandbox/internal/drivers/clock"
	"github.com/mattdowdell/sandbox/internal/drivers/config"
	"github.com/mattdowdell/sandbox/internal/drivers/config/flagoptions"
	"github.com/mattdowdell/sandbox/internal/drivers/jwtx"
	"github.com/mattdowdell/sandbox/internal/drivers/logging"
	"github.com/mattdowdell/sandbox/internal/drivers/otelx"
	"github.com/mattdowdell/sandbox/internal/drivers/pgsql"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/authn"
	logging2 "github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/logging"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/otelconnectx"
	"github.com/mattdowdell/sandbox/internal/drivers/rpcserver/interceptors/validatex"
	"github.com/mattdowdell/sandbox/internal/usecases"
)

// Injectors from wire.go:

func ProvideApp(ctx context.Context) (*App, error) {
	options := flagoptions.New()
	configConfig := config.New(options)
	mainConfig, err := LoadConfig(configConfig)
	if err != nil {
		return nil, err
	}
	loggingConfig := mainConfig.Logging
	v := loggerOptions()
	logger := logging.NewAsDefaultFromConfig(loggingConfig, v...)
	rpcserverConfig := mainConfig.RPCServer
	clockClock := clock.New()
	gen := uuid.NewGen()
	issuerConfig := mainConfig.Issuer
	issuer := jwtx.NewIssuerFromConfig(clockClock, gen, issuerConfig)
	parserConfig := mainConfig.Parser
	parser := jwtx.NewParserFromConfig(parserConfig)
	handler := authnrpc.New(issuer, parser)
	pgsqlConfig := mainConfig.Database
	db, err := pgsql.NewFromConfig(ctx, pgsqlConfig)
	if err != nil {
		return nil, err
	}
	provider := datastore.NewProvider(db)
	createResource := usecases.NewCreateResource(clockClock, gen)
	getResource := usecases.NewGetResource()
	listResources := usecases.NewListResources()
	updateResource := usecases.NewUpdateResource(clockClock)
	deleteResource := usecases.NewDeleteResource()
	resource := usecasefacades.NewResource(provider, createResource, getResource, listResources, updateResource, deleteResource)
	listAuditEvents := usecases.NewListAuditEvents()
	watchAuditEvents := usecases.NewWatchAuditEvents()
	auditEvent := usecasefacades.NewAuditEvent(provider, listAuditEvents, watchAuditEvents)
	examplerpcHandler := examplerpc.New(resource, auditEvent)
	reflectrpcHandler := reflectrpc.New()
	healthrpcHandler := healthrpc.New()
	v2 := collectHandlers(handler, examplerpcHandler, reflectrpcHandler, healthrpcHandler)
	otelconnectxConfig := mainConfig.OtelConnect
	interceptor, err := otelconnectx.NewFromConfig(otelconnectxConfig)
	if err != nil {
		return nil, err
	}
	validateInterceptor, err := validatex.New()
	if err != nil {
		return nil, err
	}
	loggingInterceptor := logging2.New()
	v3 := authnOptions()
	authnInterceptor := authn.New(v3...)
	v4 := collectInterceptors(interceptor, validateInterceptor, loggingInterceptor, authnInterceptor)
	v5 := recovererOptions()
	recoverer, err := rpcserver.NewRecoverer(v5...)
	if err != nil {
		return nil, err
	}
	v6 := collectHandlerOptions(v4, recoverer)
	server := rpcserver.NewFromConfig(rpcserverConfig, v2, v6)
	tracerProviderConfig := mainConfig.TracerProvider
	filter := baggageFilter()
	tracerProviderShutdown, err := otelx.SetupTracerProviderFromConfig(ctx, tracerProviderConfig, filter)
	if err != nil {
		return nil, err
	}
	meterProviderConfig := mainConfig.MeterProvider
	meterProviderShutdown, err := otelx.SetupMeterProviderFromConfig(ctx, meterProviderConfig)
	if err != nil {
		return nil, err
	}
	loggerProviderConfig := mainConfig.LoggerProvider
	loggerProviderShutdown, err := otelx.SetupLoggerProviderFromConfig(ctx, loggerProviderConfig, filter)
	if err != nil {
		return nil, err
	}
	app := NewApp(mainConfig, logger, server, tracerProviderShutdown, meterProviderShutdown, loggerProviderShutdown)
	return app, nil
}
