---
name: Bingo Update

inputs:
  name:
    description: The name of the tool to check for updates.
    required: true

outputs:
  updated:
    description: "Whether the version was updated."
    value: ${{ steps.updated.outputs.updates }}
  version:
    description: "The version after any updates were applied."
    value: ${{ steps.updated.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: "go.mod"

    - name: Install bingo
      uses: mattdowdell/go-installer@7af1f9ff5af1447fd122d6b144ddce2562b76e09 # v0.3.0
      with:
        package: github.com/bwplotka/bingo

    - name: Get package
      id: package
      shell: bash
      run: |
        echo "url=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f1`" >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}

    - name: Get update
      shell: bash
      run: bingo get ${PACKAGE}
      env:
        PACKAGE: ${{ steps.package.outputs.url }}

    - name: Check for update
      id: updated
      shell: bash
      run: |
        # make sure new files are included in the diff
        git add .

        if git diff HEAD --quiet -- .
        then
          echo "updated=false" >> "$GITHUB_OUTPUT"
        else
          echo "updated=true" >> "$GITHUB_OUTPUT"
        fi

        echo "version=`bingo list | \
          tail -n+3 | \
          grep '^${NAME}\b' | \
          awk '{print $3}' | `
          cut -d@ -f2` >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}
