---
name: Bingo Update

inputs:
  name:
    description: The name of the tool to check for updates.
    required: true
  dry-run:
    description: Whether to run the update in dry-run mode.
    required: true

outputs:
  current:
    description: "The current version for the tool."
    value: ${{ steps.package.outputs.version }}
  updated:
    description: "Whether the version was updated."
    value: ${{ steps.updated.outputs.updated }}
  latest:
    description: "The latest available version for the tool."
    value: ${{ steps.updated.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: "go.mod"

    - name: Install bingo
      uses: mattdowdell/go-installer@7af1f9ff5af1447fd122d6b144ddce2562b76e09 # v0.3.0
      with:
        package: github.com/bwplotka/bingo

    - name: Get package
      id: package
      shell: bash
      run: |
        echo "url=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f1`" >> "$GITHUB_OUTPUT"
        echo "version=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f2`" >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}

    - name: Get update
      shell: bash
      run: bingo get ${PACKAGE}@latest
      env:
        PACKAGE: ${{ steps.package.outputs.url }}

    - name: Check for update
      id: updated
      shell: bash
      run: |
        # make sure new files are included in the diff
        git add .

        if git diff HEAD --quiet -- .
        then
          echo "updated=false" >> "$GITHUB_OUTPUT"
        else
          echo "updated=true" >> "$GITHUB_OUTPUT"
        fi

        echo "version=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f2`" >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}

    - name: Setup checks
      if: steps.updated.outputs.updated == "true"
      uses: ./.github/actions/setup-checks

    - name: Start database
      if: steps.updated.outputs.updated == "true"
      uses: hoverkraft-tech/compose-action@40041ff1b97dbf152cd2361138c2b03fa29139df # v2.3.0
      with:
        compose-file: compose.yaml
        up-flags: --build --wait
        down-flags: --volumes --remove-orphans
        services: |
          postgres
          migrate

    - name: Regenerate
      if: steps.updated.outputs.updated == "true"
      shell: bash
      run: |
        # do for tool updates first and separately, otherwise other commands will fail
        just gen-tools
        just checks

    - name: Create PR
      if: steps.updated.outputs.updated == "true" && inputs.dry-run != false
      shell: bash
      run: |
        # make sure new files are included in the diff
        git add .
        git diff HEAD -- .

        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git switch --create tool-update/${NAME}-${LATEST}

        git commit -m "Update ${NAME} from ${CURRENT} to ${LATEST}"
        git push --set-upstream-to origin tool-update/${NAME}-${LATEST}
      env:
        NAME: ${{ inputs.name }}
        CURRENT: ${{ steps.package.outputs.version }}
        LATEST: ${{ steps.updated.outputs.version }}
