---
name: Bingo Update
description: Update a tool managed by Bingo.

inputs:
  name:
    description: The name of the tool to check for updates.
    required: true
  dry-run:
    description: Whether to run the update in dry-run mode.
    required: true

outputs:
  current:
    description: "The current version for the tool."
    value: ${{ steps.package.outputs.version }}
  updated:
    description: "Whether the version was updated."
    value: ${{ steps.updated.outputs.updated }}
  latest:
    description: "The latest available version for the tool."
    value: ${{ steps.updated.outputs.version }}

runs:
  using: composite
  steps:
    - name: Install Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version-file: "go.mod"

    - name: Install bingo
      uses: mattdowdell/go-installer@de5d072ade9fc895652cd6a93ac4bde11e105bc6 # v0.4.0
      with:
        package: github.com/bwplotka/bingo

    - name: Get package
      id: package
      shell: bash
      run: |
        echo "url=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f1`" >> "$GITHUB_OUTPUT"
        echo "version=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f2`" >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}

    - name: Get update
      shell: bash
      run: bingo get ${PACKAGE}@latest
      env:
        PACKAGE: ${{ steps.package.outputs.url }}

    - name: Check for update
      id: updated
      shell: bash
      run: |
        # make sure new files are included in the diff
        git add .

        if git diff HEAD --quiet -- .
        then
          echo "updated=false" >> "$GITHUB_OUTPUT"
        else
          echo "updated=true" >> "$GITHUB_OUTPUT"
        fi

        echo "version=`bingo list | \
          tail -n+3 | \
          grep "^${NAME}\b" | \
          awk '{print $3}' | \
          cut -d@ -f2`" >> "$GITHUB_OUTPUT"
      env:
        NAME: ${{ inputs.name }}
