{
 "title": "Database",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(db.client.operation.duration_bucket,service.name)"
    }
   },
   {
    "name": "service_instance_id",
    "label": "Service Instance ID",
    "query": {
     "query": "label_values(db.client.operation.duration_bucket{service.name=\"$service_name\"},service.instance.id)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(db.client.operation.duration_bucket{service.name=\"$service_name\",service.instance.id=~\"$service_instance_id\"},db.operation.name)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": "All : error.type=~\".*\" , Success : error.type=\"\" ,Error : error.type!=\"\""
   }
  ]
 },
 "panels": [
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "P99 Average (Success)",
   "type": "stat",
   "description": "The P99 latency for success responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p99 {{method}}"
    }
   ]
  },
  {
   "title": "P99 Average (Error)",
   "type": "stat",
   "description": "The P99 latency for error responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p99 {{method}}"
    }
   ]
  },
  {
   "title": "P90 Average (Success)",
   "type": "stat",
   "description": "The P90 latency for success responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p90 {{method}}"
    }
   ]
  },
  {
   "title": "P90 Average (Error)",
   "type": "stat",
   "description": "The P90 latency for error responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p90 {{method}}"
    }
   ]
  },
  {
   "title": "P50 Average (Success)",
   "type": "stat",
   "description": "The P50 latency for success responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p50 {{method}}"
    }
   ]
  },
  {
   "title": "P50 Average (Error)",
   "type": "stat",
   "description": "The P50 latency for error database responses, averaged across the current time range.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p50 {{method}}"
    }
   ]
  },
  {
   "title": "Overall",
   "type": "timeseries",
   "description": "Latency for all responses over time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\"}[$__interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\"}[$__interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\"}[$__interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Success",
   "type": "timeseries",
   "description": "Latency for success responses over time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type=\"\"}[$__interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "description": "Latency for error responses over time.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p99 {{method}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p90 {{method}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (increase(db.client.operation.duration_bucket{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",error.type!=\"\"}[$__interval])))",
     "legendFormat": "p50 {{method}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total",
   "type": "piechart",
   "description": "Total count of each method and status combination across the current time range.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(db.operation.name) (increase(db.client.operation.duration_count{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",$status}[$__interval]))",
     "legendFormat": "{{db.operation.name}}"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "timeseries",
   "description": "Number of each method and status combination over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(db.operation.name) (increase(db.client.operation.duration_count{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\",db.operation.name=~\"$operation\",$status}[$__interval]))",
     "legendFormat": "{{db.operation.name}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Current Open Connections",
   "type": "stat",
   "description": "The current number of open connections.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status) (db.sql.connection.open{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Waiting Connections",
   "type": "stat",
   "description": "The current number of connections being waited for.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db.sql.connection.wait{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"}))",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Current Closed Connections",
   "type": "stat",
   "description": "The current number of closed connections.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(db.sql.connection.closed_max_idle{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"}))",
     "legendFormat": "MaxIdle"
    },
    {
     "expr": "sum(increase(db.sql.connection.closed_max_idle_time{}))",
     "legendFormat": "MaxIdleTime"
    },
    {
     "expr": "sum(increase(db.sql.connection.closed_max_lifetime{}))",
     "legendFormat": "MaxLifetime"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "description": "The number of open connections over time.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status) (db.sql.connection.open{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Waiting Connections",
   "type": "timeseries",
   "description": "The number of connections being waited for over time.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(db.sql.connection.wait{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"}))",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "description": "The number of closed connections over time.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(db.sql.connection.closed_max_idle{service.name=~\"$service_name\",service.instance.id=~\"$service_instance_id\"}))",
     "legendFormat": "MaxIdle"
    },
    {
     "expr": "sum(increase(db.sql.connection.closed_max_idle_time{}))",
     "legendFormat": "MaxIdleTime"
    },
    {
     "expr": "sum(increase(db.sql.connection.closed_max_lifetime{}))",
     "legendFormat": "MaxLifetime"
    }
   ]
  }
 ]
}