syntax = "proto3";

package example.v1;

import "example/v1/messages.proto";

option go_package = "github.com/mattdowdell/sandbox/gen/example/v1;examplev1";

// ...
service ExampleService {
  // ...
  rpc CreateResource(CreateResourceRequest) returns (CreateResourceResponse) {}

  // ...
  rpc GetResource(GetResourceRequest) returns (GetResourceResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // ...
  rpc ListResources(ListResourcesRequest) returns (ListResourcesResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // ...
  rpc UpdateResource(UpdateResourceRequest) returns (UpdateResourceResponse) {}

  // ...
  rpc DeleteResource(DeleteResourceRequest) returns (DeleteResourceResponse) {}

  // ...
  rpc ListAuditEvents(ListAuditEventsRequest) returns (ListAuditEventsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }

  // ...
  rpc WatchAuditEvents(WatchAuditEventsRequest) returns (stream WatchAuditEventsResponse) {}
}
