---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-dashboards
    options:
      disableNameSuffixHash: true
    files:
      - connectrpc.json
      - database.json
      - go_runtime.json
      - grpc.json
