---
name: "Setup Checks"

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: "go.mod"

    - name: Install Buf
      uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0
      with:
        setup_only: true

    - name: Install Just
      uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

    - name: Install bingo
      uses: mattdowdell/go-installer@7af1f9ff5af1447fd122d6b144ddce2562b76e09 # v0.3.0
      with:
        package: github.com/bwplotka/bingo
