name: "Setup Checks"

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version-file: "go.mod"

    - name: Install Buf
      uses: bufbuild/buf-action@b46cbc051dd8fd10a3c2213e784498790d3fe388 # v1.0.3
      with:
        setup_only: true

    - name: Install Just
      uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2.0.0

    - name: Install gci
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: github.com/daixiang0/gci
        version-file: go.mod

    - name: Install gofumpt
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: mvdan.cc/gofumpt
        version-file: go.mod

    - name: Install mockery
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: github.com/vektra/mockery/v2
        version-file: go.mod

    - name: Install protoc-gen-connect-go
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: connectrpc.com/connect/cmd/protoc-gen-connect-go
        version-file: go.mod

    - name: Install protoc-gen-go
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: google.golang.org/protobuf/cmd/protoc-gen-go
        version-file: go.mod

    - name: Install wire
      uses: mattdowdell/go-installer@v0.2.0
      with:
        package: github.com/google/wire/cmd/wire
        version-file: go.mod
