---
name: "Setup Checks"
description: Setup a runner for running 'just checks'.

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: "go.mod"

    - name: Install Buf
      uses: bufbuild/buf-action@8c6a16e16f12ba20b6470afa9c2ba9b5ba8c97c3 # v1.5.0
      with:
        setup_only: true

    - name: Install Just
      uses: taiki-e/install-action@67729d5c413db75907f0ad1e39bb04b9c868ff60 # v2.85.7
      with:
        tool: just

    - name: Install bingo
      uses: mattdowdell/go-installer@de5d072ade9fc895652cd6a93ac4bde11e105bc6 # v0.4.0
      with:
        package: github.com/bwplotka/bingo
