---
name: "Setup Checks"
description: Setup a runner for running 'just checks'.

runs:
  using: "composite"
  steps:
    - name: Install Go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: "go.mod"

    - name: Install Buf
      uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
      with:
        setup_only: true

    - name: Install Just
      uses: taiki-e/install-action@43aecc8d72668fbcfe75c31400bc4f890f1c5853 # v2.83.2
      with:
        tool: just

    - name: Install bingo
      uses: mattdowdell/go-installer@de5d072ade9fc895652cd6a93ac4bde11e105bc6 # v0.4.0
      with:
        package: github.com/bwplotka/bingo
