// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocktxn

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/adapters/txn"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	"github.com/mattdowdell/sandbox/internal/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatastore creates a new instance of MockDatastore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastore {
	mock := &MockDatastore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatastore is an autogenerated mock type for the Datastore type
type MockDatastore struct {
	mock.Mock
}

type MockDatastore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastore) EXPECT() *MockDatastore_Expecter {
	return &MockDatastore_Expecter{mock: &_m.Mock}
}

// CreateAuditEvent provides a mock function for the type MockDatastore
func (_mock *MockDatastore) CreateAuditEvent(context1 context.Context, auditEvent *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_CreateAuditEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditEvent'
type MockDatastore_CreateAuditEvent_Call struct {
	*mock.Call
}

// CreateAuditEvent is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEvent *entities.AuditEvent
func (_e *MockDatastore_Expecter) CreateAuditEvent(context1 interface{}, auditEvent interface{}) *MockDatastore_CreateAuditEvent_Call {
	return &MockDatastore_CreateAuditEvent_Call{Call: _e.mock.On("CreateAuditEvent", context1, auditEvent)}
}

func (_c *MockDatastore_CreateAuditEvent_Call) Run(run func(context1 context.Context, auditEvent *entities.AuditEvent)) *MockDatastore_CreateAuditEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(*entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_CreateAuditEvent_Call) Return(err error) *MockDatastore_CreateAuditEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_CreateAuditEvent_Call) RunAndReturn(run func(context1 context.Context, auditEvent *entities.AuditEvent) error) *MockDatastore_CreateAuditEvent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type MockDatastore
func (_mock *MockDatastore) CreateResource(context1 context.Context, resource *entities.Resource) error {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) error); ok {
		r0 = returnFunc(context1, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type MockDatastore_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *MockDatastore_Expecter) CreateResource(context1 interface{}, resource interface{}) *MockDatastore_CreateResource_Call {
	return &MockDatastore_CreateResource_Call{Call: _e.mock.On("CreateResource", context1, resource)}
}

func (_c *MockDatastore_CreateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *MockDatastore_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_CreateResource_Call) Return(err error) *MockDatastore_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_CreateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) error) *MockDatastore_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type MockDatastore
func (_mock *MockDatastore) DeleteResource(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type MockDatastore_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockDatastore_Expecter) DeleteResource(context1 interface{}, uUID interface{}) *MockDatastore_DeleteResource_Call {
	return &MockDatastore_DeleteResource_Call{Call: _e.mock.On("DeleteResource", context1, uUID)}
}

func (_c *MockDatastore_DeleteResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockDatastore_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_DeleteResource_Call) Return(err error) *MockDatastore_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_DeleteResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockDatastore_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type MockDatastore
func (_mock *MockDatastore) GetResource(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type MockDatastore_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockDatastore_Expecter) GetResource(context1 interface{}, uUID interface{}) *MockDatastore_GetResource_Call {
	return &MockDatastore_GetResource_Call{Call: _e.mock.On("GetResource", context1, uUID)}
}

func (_c *MockDatastore_GetResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockDatastore_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_GetResource_Call) Return(resource *entities.Resource, err error) *MockDatastore_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockDatastore_GetResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error)) *MockDatastore_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditEvents provides a mock function for the type MockDatastore
func (_mock *MockDatastore) ListAuditEvents(context1 context.Context) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditEvents")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_ListAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditEvents'
type MockDatastore_ListAuditEvents_Call struct {
	*mock.Call
}

// ListAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockDatastore_Expecter) ListAuditEvents(context1 interface{}) *MockDatastore_ListAuditEvents_Call {
	return &MockDatastore_ListAuditEvents_Call{Call: _e.mock.On("ListAuditEvents", context1)}
}

func (_c *MockDatastore_ListAuditEvents_Call) Run(run func(context1 context.Context)) *MockDatastore_ListAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatastore_ListAuditEvents_Call) Return(auditEvents []*entities.AuditEvent, err error) *MockDatastore_ListAuditEvents_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *MockDatastore_ListAuditEvents_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.AuditEvent, error)) *MockDatastore_ListAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type MockDatastore
func (_mock *MockDatastore) ListResources(context1 context.Context, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error) {
	ret := _mock.Called(context1, pager)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 *repositories.Paged[*entities.Resource]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.Pager) (*repositories.Paged[*entities.Resource], error)); ok {
		return returnFunc(context1, pager)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.Pager) *repositories.Paged[*entities.Resource]); ok {
		r0 = returnFunc(context1, pager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.Paged[*entities.Resource])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.Pager) error); ok {
		r1 = returnFunc(context1, pager)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockDatastore_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - context1 context.Context
//   - pager repositories.Pager
func (_e *MockDatastore_Expecter) ListResources(context1 interface{}, pager interface{}) *MockDatastore_ListResources_Call {
	return &MockDatastore_ListResources_Call{Call: _e.mock.On("ListResources", context1, pager)}
}

func (_c *MockDatastore_ListResources_Call) Run(run func(context1 context.Context, pager repositories.Pager)) *MockDatastore_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.Pager
		if args[1] != nil {
			arg1 = args[1].(repositories.Pager)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_ListResources_Call) Return(paged *repositories.Paged[*entities.Resource], err error) *MockDatastore_ListResources_Call {
	_c.Call.Return(paged, err)
	return _c
}

func (_c *MockDatastore_ListResources_Call) RunAndReturn(run func(context1 context.Context, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error)) *MockDatastore_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type MockDatastore
func (_mock *MockDatastore) UpdateResource(context1 context.Context, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Resource) error); ok {
		r1 = returnFunc(context1, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type MockDatastore_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *MockDatastore_Expecter) UpdateResource(context1 interface{}, resource interface{}) *MockDatastore_UpdateResource_Call {
	return &MockDatastore_UpdateResource_Call{Call: _e.mock.On("UpdateResource", context1, resource)}
}

func (_c *MockDatastore_UpdateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *MockDatastore_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_UpdateResource_Call) Return(resource1 *entities.Resource, err error) *MockDatastore_UpdateResource_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *MockDatastore_UpdateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) (*entities.Resource, error)) *MockDatastore_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAuditEvents provides a mock function for the type MockDatastore
func (_mock *MockDatastore) WatchAuditEvents(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEventCh)

	if len(ret) == 0 {
		panic("no return value specified for WatchAuditEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan<- *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEventCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_WatchAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAuditEvents'
type MockDatastore_WatchAuditEvents_Call struct {
	*mock.Call
}

// WatchAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEventCh chan<- *entities.AuditEvent
func (_e *MockDatastore_Expecter) WatchAuditEvents(context1 interface{}, auditEventCh interface{}) *MockDatastore_WatchAuditEvents_Call {
	return &MockDatastore_WatchAuditEvents_Call{Call: _e.mock.On("WatchAuditEvents", context1, auditEventCh)}
}

func (_c *MockDatastore_WatchAuditEvents_Call) Run(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent)) *MockDatastore_WatchAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(chan<- *entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_WatchAuditEvents_Call) Return(err error) *MockDatastore_WatchAuditEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_WatchAuditEvents_Call) RunAndReturn(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error) *MockDatastore_WatchAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEnder creates a new instance of MockEnder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEnder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEnder {
	mock := &MockEnder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEnder is an autogenerated mock type for the Ender type
type MockEnder struct {
	mock.Mock
}

type MockEnder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEnder) EXPECT() *MockEnder_Expecter {
	return &MockEnder_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function for the type MockEnder
func (_mock *MockEnder) Commit() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnder_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockEnder_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
func (_e *MockEnder_Expecter) Commit() *MockEnder_Commit_Call {
	return &MockEnder_Commit_Call{Call: _e.mock.On("Commit")}
}

func (_c *MockEnder_Commit_Call) Run(run func()) *MockEnder_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnder_Commit_Call) Return(err error) *MockEnder_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnder_Commit_Call) RunAndReturn(run func() error) *MockEnder_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockEnder
func (_mock *MockEnder) Rollback() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEnder_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockEnder_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
func (_e *MockEnder_Expecter) Rollback() *MockEnder_Rollback_Call {
	return &MockEnder_Rollback_Call{Call: _e.mock.On("Rollback")}
}

func (_c *MockEnder_Rollback_Call) Run(run func()) *MockEnder_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEnder_Rollback_Call) Return(err error) *MockEnder_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEnder_Rollback_Call) RunAndReturn(run func() error) *MockEnder_Rollback_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function for the type MockProvider
func (_mock *MockProvider) BeginTx(context1 context.Context) (txn.Datastore, txn.Ender, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 txn.Datastore
	var r1 txn.Ender
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (txn.Datastore, txn.Ender, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) txn.Datastore); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txn.Datastore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) txn.Ender); ok {
		r1 = returnFunc(context1)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(txn.Ender)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = returnFunc(context1)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProvider_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockProvider_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockProvider_Expecter) BeginTx(context1 interface{}) *MockProvider_BeginTx_Call {
	return &MockProvider_BeginTx_Call{Call: _e.mock.On("BeginTx", context1)}
}

func (_c *MockProvider_BeginTx_Call) Run(run func(context1 context.Context)) *MockProvider_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProvider_BeginTx_Call) Return(datastore txn.Datastore, ender txn.Ender, err error) *MockProvider_BeginTx_Call {
	_c.Call.Return(datastore, ender, err)
	return _c
}

func (_c *MockProvider_BeginTx_Call) RunAndReturn(run func(context1 context.Context) (txn.Datastore, txn.Ender, error)) *MockProvider_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Datastore provides a mock function for the type MockProvider
func (_mock *MockProvider) Datastore() txn.Datastore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Datastore")
	}

	var r0 txn.Datastore
	if returnFunc, ok := ret.Get(0).(func() txn.Datastore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(txn.Datastore)
		}
	}
	return r0
}

// MockProvider_Datastore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Datastore'
type MockProvider_Datastore_Call struct {
	*mock.Call
}

// Datastore is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Datastore() *MockProvider_Datastore_Call {
	return &MockProvider_Datastore_Call{Call: _e.mock.On("Datastore")}
}

func (_c *MockProvider_Datastore_Call) Run(run func()) *MockProvider_Datastore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Datastore_Call) Return(datastore txn.Datastore) *MockProvider_Datastore_Call {
	_c.Call.Return(datastore)
	return _c
}

func (_c *MockProvider_Datastore_Call) RunAndReturn(run func() txn.Datastore) *MockProvider_Datastore_Call {
	_c.Call.Return(run)
	return _c
}
