name: Tag

inputs:
  format:
    # TODO: implement incrementing, year-week.
    # year-week will be awkward because of how ISO weeks work, see Go's time ISOWeek for inspiration.
    description: "One of: incrementing, year-month, year-week."
    required: false
    default: "incrementing"

outputs:
  short:
    description: "The output of 'git describe'."
    value: ${{ steps.describe.outputs.short }}
  long:
    description: "The output of 'git describe --long'."
    value: ${{ steps.describe.outputs.long }}

runs:
  using: "composite"
  steps:
    # TODO: check we have a deep checkout
    - name: Check
      shell: bash
      run: |
        echo "Not implemented"

    - name: Next
      # TODO: uncomment
      # if: github.ref_name == github.event.repository.default_branch
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const path = require('path');

          const script = require(path.join(process.env.GITHUB_ACTION_PATH, 'next.js'));
          await script({ exec });

    - name: Describe
      id: describe
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const path = require('path');

          const script = require(path.join(process.env.GITHUB_ACTION_PATH, 'describe.js'));
          await script({ exec });

