// Code generated by mockery. DO NOT EDIT.

package mockcommon

import mock "github.com/stretchr/testify/mock"

// RollbackFn is an autogenerated mock type for the RollbackFn type
type RollbackFn struct {
	mock.Mock
}

type RollbackFn_Expecter struct {
	mock *mock.Mock
}

func (_m *RollbackFn) EXPECT() *RollbackFn_Expecter {
	return &RollbackFn_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with no fields
func (_m *RollbackFn) Execute() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackFn_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type RollbackFn_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *RollbackFn_Expecter) Execute() *RollbackFn_Execute_Call {
	return &RollbackFn_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *RollbackFn_Execute_Call) Run(run func()) *RollbackFn_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RollbackFn_Execute_Call) Return(_a0 error) *RollbackFn_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *RollbackFn_Execute_Call) RunAndReturn(run func() error) *RollbackFn_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewRollbackFn creates a new instance of RollbackFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRollbackFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *RollbackFn {
	mock := &RollbackFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
