---

config:
  database_sslmode: "disable"
  logging_level: "debug"
  rpcserver_enablepprof: "true"

deployments:
  example-rpc:
    # TODO: labels
    # TODO: annotations
    replicas: 2
    containers:
      - name: example-rpc
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-rpc
          # tag: latest
        env:
          # GOCOVERDIR: "/covdata"
          OTEL_GO_X_DEPRECATED_RUNTIME_METRICS: "false"
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

jobs:
  example-db-migrate:
    # TODO: labels
    # TODO: annotations
    containers:
      - name: example-db-migrate
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-db-migrate
          tag: latest
        env:
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

# TODO: services
# TODO: ingress

