---

nameOverride: "example"
fullnameOverride: ""

configmaps:
  # TODO: labels
  # TODO: annotations
  example:
    data:
      shutdowntimeout: "30s"
      authn_address: ""
      database_hostname: ""
      database_port: "5432"
      database_username: ""
      database_password: ""
      database_useiamauth: "false"
      database_region: ""
      database_name: ""
      database_sslmode: "verify-full"
      database_maxidletime: "5m"
      database_maxlifetime: "5m"
      database_maxidleconns: "0"
      database_maxopenconns: "0"
      issuer_audience: ""
      issuer_issuer: ""
      logging_level: "info"
      logging_legacylevel: "debug"
      loggerprovider_insecure: "false"
      loggerprovider_endpoint: ""
      loggerprovider_path: "/v1/logs"
      meterprovider_insecure: "false"
      meterprovider_endpoint: ""
      meterprovider_path: "/v1/metrics"
      otelconnect_trustremote: "false"
      parser_audience: ""
      parser_issuer: ""
      parser_methods: ""
      rpcserver_host: "localhost"
      rpcserver_port: "5000"
      rpcserver_enablepprof: "false"
      tracerprovider_insecure: "false"
      tracerprovider_endpoint: ""
      tracerprovider_path: "/v1/traces"

serviceAccount:
  create: true
  automount: true

# TODO: role
# TODO: role binding

deployments:
  example-rpc:
    # TODO: labels
    # TODO: annotations
    replicas: 2
    containers:
      example-rpc:
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-rpc
          # tag: latest
        env:
          # GOCOVERDIR: "/covdata"
          OTEL_GO_X_DEPRECATED_RUNTIME_METRICS: "false"
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

jobs:
  example-db-migrate:
    # TODO: labels
    # TODO: annotations
    containers:
      example-db-migrate:
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-db-migrate
          tag: latest
        env:
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

# TODO: services
# TODO: ingress

