---

nameOverride: example

config:
  # TODO: labels
  # TODO: annotations
  authn_address: "http://localhost:5000"
  database_hostname: "cluster-postgresql-rw.default.svc.cluster.local"
  # database_sslmode: "disable"
  issuer_audience: "example"
  issuer_issuer: "example"
  # logging_level: "debug"
  parser_audience: "example"
  parser_issuer: "example"
  parser_methods: "HS256"
  rpcserver_host: "0.0.0.0"
  # rpcserver_enablepprof: "true"
  meterprovider_insecure: "true"
  meterprovider_endpoint: "victoria-metrics-single-server.default.svc.cluster.local:8428"
  meterprovider_path: "/opentelemetry/v1/metrics"
  tracerprovider_insecure: "true"
  tracerprovider_endpoint: "tempo.default.svc.cluster.local:4318"
  # TODO: tracerprovider_path? /v1/traces
  loggerprovider_insecure: "true"
  loggerprovider_endpoint: "victoria-logs-single-server.default.svc.cluster.local:9428"
  loggerprovider_path: "/insert/opentelemetry/v1/logs"

# TODO: service account
# TODO: role
# TODO: role binding

deployments:
  example-rpc:
    # TODO: labels
    # TODO: annotations
    replicas: 2
    containers:
      example-rpc:
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-rpc
          # tag: latest
        env:
          # GOCOVERDIR: "/covdata"
          OTEL_GO_X_DEPRECATED_RUNTIME_METRICS: "false"
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

jobs:
  example-db-migrate:
    # TODO: labels
    # TODO: annotations
    containers:
      example-db-migrate:
        # TODO: labels
        # TODO: annotations
        image:
          repository: example-db-migrate
          tag: latest
        env:
          CONFIG_MOUNTS: "/etc/example:/etc/postgresql"
    configmaps:
      - name: example
        mountPath: /etc/example
    secrets:
      - name: cluster-postgresql-app
        mountPath: /etc/postgresql
        items:
          - key: password
            path: database_password
          - key: username
            path: database_username
          - key: dbname
            path: database_name

# TODO: services
# TODO: ingress

