// Code generated by mockery v2.50.4. DO NOT EDIT.

package mockexamplerpc

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ResourceDeleter is an autogenerated mock type for the ResourceDeleter type
type ResourceDeleter struct {
	mock.Mock
}

type ResourceDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceDeleter) EXPECT() *ResourceDeleter_Expecter {
	return &ResourceDeleter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *ResourceDeleter) Execute(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResourceDeleter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ResourceDeleter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *ResourceDeleter_Expecter) Execute(_a0 interface{}, _a1 interface{}) *ResourceDeleter_Execute_Call {
	return &ResourceDeleter_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *ResourceDeleter_Execute_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *ResourceDeleter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *ResourceDeleter_Execute_Call) Return(_a0 error) *ResourceDeleter_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceDeleter_Execute_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *ResourceDeleter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceDeleter creates a new instance of ResourceDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceDeleter {
	mock := &ResourceDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
