// Code generated by mockery v2.50.4. DO NOT EDIT.

package mockexamplerpc

import (
	context "context"

	entities "github.com/mattdowdell/sandbox/internal/domain/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuditEventWatcher is an autogenerated mock type for the AuditEventWatcher type
type AuditEventWatcher struct {
	mock.Mock
}

type AuditEventWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventWatcher) EXPECT() *AuditEventWatcher_Expecter {
	return &AuditEventWatcher_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *AuditEventWatcher) Execute(_a0 context.Context) <-chan *entities.AuditEvent {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan *entities.AuditEvent
	if rf, ok := ret.Get(0).(func(context.Context) <-chan *entities.AuditEvent); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.AuditEvent)
		}
	}

	return r0
}

// AuditEventWatcher_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type AuditEventWatcher_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *AuditEventWatcher_Expecter) Execute(_a0 interface{}) *AuditEventWatcher_Execute_Call {
	return &AuditEventWatcher_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *AuditEventWatcher_Execute_Call) Run(run func(_a0 context.Context)) *AuditEventWatcher_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AuditEventWatcher_Execute_Call) Return(_a0 <-chan *entities.AuditEvent) *AuditEventWatcher_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuditEventWatcher_Execute_Call) RunAndReturn(run func(context.Context) <-chan *entities.AuditEvent) *AuditEventWatcher_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventWatcher creates a new instance of AuditEventWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventWatcher {
	mock := &AuditEventWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
