// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockexamplerpc

import (
	"context"
	"log/slog"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewResourceFacade creates a new instance of ResourceFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceFacade {
	mock := &ResourceFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ResourceFacade is an autogenerated mock type for the ResourceFacade type
type ResourceFacade struct {
	mock.Mock
}

type ResourceFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceFacade) EXPECT() *ResourceFacade_Expecter {
	return &ResourceFacade_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ResourceFacade
func (_mock *ResourceFacade) Create(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceFacade_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ResourceFacade_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource *entities.Resource
func (_e *ResourceFacade_Expecter) Create(context1 interface{}, logger interface{}, resource interface{}) *ResourceFacade_Create_Call {
	return &ResourceFacade_Create_Call{Call: _e.mock.On("Create", context1, logger, resource)}
}

func (_c *ResourceFacade_Create_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource)) *ResourceFacade_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 *entities.Resource
		if args[2] != nil {
			arg2 = args[2].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceFacade_Create_Call) Return(resource1 *entities.Resource, err error) *ResourceFacade_Create_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *ResourceFacade_Create_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error)) *ResourceFacade_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ResourceFacade
func (_mock *ResourceFacade) Delete(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) error {
	ret := _mock.Called(context1, logger, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) error); ok {
		r0 = returnFunc(context1, logger, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ResourceFacade_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ResourceFacade_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - uUID uuid.UUID
func (_e *ResourceFacade_Expecter) Delete(context1 interface{}, logger interface{}, uUID interface{}) *ResourceFacade_Delete_Call {
	return &ResourceFacade_Delete_Call{Call: _e.mock.On("Delete", context1, logger, uUID)}
}

func (_c *ResourceFacade_Delete_Call) Run(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID)) *ResourceFacade_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceFacade_Delete_Call) Return(err error) *ResourceFacade_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ResourceFacade_Delete_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) error) *ResourceFacade_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type ResourceFacade
func (_mock *ResourceFacade) Get(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, uuid.UUID) error); ok {
		r1 = returnFunc(context1, logger, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceFacade_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ResourceFacade_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - uUID uuid.UUID
func (_e *ResourceFacade_Expecter) Get(context1 interface{}, logger interface{}, uUID interface{}) *ResourceFacade_Get_Call {
	return &ResourceFacade_Get_Call{Call: _e.mock.On("Get", context1, logger, uUID)}
}

func (_c *ResourceFacade_Get_Call) Run(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID)) *ResourceFacade_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceFacade_Get_Call) Return(resource *entities.Resource, err error) *ResourceFacade_Get_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *ResourceFacade_Get_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, uUID uuid.UUID) (*entities.Resource, error)) *ResourceFacade_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ResourceFacade
func (_mock *ResourceFacade) List(context1 context.Context, logger *slog.Logger) ([]*entities.Resource, error) {
	ret := _mock.Called(context1, logger)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) ([]*entities.Resource, error)); ok {
		return returnFunc(context1, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) []*entities.Resource); ok {
		r0 = returnFunc(context1, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger) error); ok {
		r1 = returnFunc(context1, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ResourceFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
func (_e *ResourceFacade_Expecter) List(context1 interface{}, logger interface{}) *ResourceFacade_List_Call {
	return &ResourceFacade_List_Call{Call: _e.mock.On("List", context1, logger)}
}

func (_c *ResourceFacade_List_Call) Run(run func(context1 context.Context, logger *slog.Logger)) *ResourceFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ResourceFacade_List_Call) Return(resources []*entities.Resource, err error) *ResourceFacade_List_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *ResourceFacade_List_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger) ([]*entities.Resource, error)) *ResourceFacade_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ResourceFacade
func (_mock *ResourceFacade) Update(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ResourceFacade_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ResourceFacade_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource *entities.Resource
func (_e *ResourceFacade_Expecter) Update(context1 interface{}, logger interface{}, resource interface{}) *ResourceFacade_Update_Call {
	return &ResourceFacade_Update_Call{Call: _e.mock.On("Update", context1, logger, resource)}
}

func (_c *ResourceFacade_Update_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource)) *ResourceFacade_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 *entities.Resource
		if args[2] != nil {
			arg2 = args[2].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *ResourceFacade_Update_Call) Return(resource1 *entities.Resource, err error) *ResourceFacade_Update_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *ResourceFacade_Update_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource *entities.Resource) (*entities.Resource, error)) *ResourceFacade_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuditEventFacade creates a new instance of AuditEventFacade. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEventFacade(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEventFacade {
	mock := &AuditEventFacade{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditEventFacade is an autogenerated mock type for the AuditEventFacade type
type AuditEventFacade struct {
	mock.Mock
}

type AuditEventFacade_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEventFacade) EXPECT() *AuditEventFacade_Expecter {
	return &AuditEventFacade_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type AuditEventFacade
func (_mock *AuditEventFacade) List(context1 context.Context, logger *slog.Logger) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1, logger)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1, logger)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger) error); ok {
		r1 = returnFunc(context1, logger)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuditEventFacade_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditEventFacade_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
func (_e *AuditEventFacade_Expecter) List(context1 interface{}, logger interface{}) *AuditEventFacade_List_Call {
	return &AuditEventFacade_List_Call{Call: _e.mock.On("List", context1, logger)}
}

func (_c *AuditEventFacade_List_Call) Run(run func(context1 context.Context, logger *slog.Logger)) *AuditEventFacade_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditEventFacade_List_Call) Return(auditEvents []*entities.AuditEvent, err error) *AuditEventFacade_List_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *AuditEventFacade_List_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger) ([]*entities.AuditEvent, error)) *AuditEventFacade_List_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function for the type AuditEventFacade
func (_mock *AuditEventFacade) Watch(context1 context.Context, logger *slog.Logger) <-chan *entities.AuditEvent {
	ret := _mock.Called(context1, logger)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 <-chan *entities.AuditEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger) <-chan *entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.AuditEvent)
		}
	}
	return r0
}

// AuditEventFacade_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type AuditEventFacade_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
func (_e *AuditEventFacade_Expecter) Watch(context1 interface{}, logger interface{}) *AuditEventFacade_Watch_Call {
	return &AuditEventFacade_Watch_Call{Call: _e.mock.On("Watch", context1, logger)}
}

func (_c *AuditEventFacade_Watch_Call) Run(run func(context1 context.Context, logger *slog.Logger)) *AuditEventFacade_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditEventFacade_Watch_Call) Return(auditEventCh <-chan *entities.AuditEvent) *AuditEventFacade_Watch_Call {
	_c.Call.Return(auditEventCh)
	return _c
}

func (_c *AuditEventFacade_Watch_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger) <-chan *entities.AuditEvent) *AuditEventFacade_Watch_Call {
	_c.Call.Return(run)
	return _c
}
