name: Container Build

inputs:
  service:
    description: "The service to build, used as a build argument."
    required: true
  repository:
    description: "The container repository, used for tagging."
    required: true
  version:
    description: "The version of the image, used for tagging and annotations."
    required: true
  push:
    description: "Whether to push the built image."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Build
      uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      id: build
      with:
        annotations: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.version=${{ inputs.version }}
        build-args:
          SERVICE=${{ inputs.service }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        push: ${{ inputs.push }}
        tags: ${{ inputs.repository }}:${{ inputs.version }}
        target: runtime
        # TODO: provenance=max
        # TODO: sbom=true
      env:
        SOURCE_DATE_EPOCH: 0

    - name: Scan
      uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # 0.30.0
      with:
        image-ref: ${{ inputs.repository }}:${{ inputs.version }}
        scan-type: image
        trivy-config: trivy.yaml

    # TODO: publish to github for default branch builds
    # https://github.com/actions/starter-workflows/blob/main/code-scanning/trivy.yml

    - name: Cosign
      shell: bash
      if: ${{ inputs.push }}
      run: |
        cosign sign --yes ${service}:${version}@${digest}
      env:
        service: ${{ inputs.service }}
        version: ${{ inputs.version }}
        digest: ${{ steps.build.outputs.digest }}
