---
name: Container Build

inputs:
  service:
    description: "The service to build, used as a build argument."
    required: true
  repository:
    description: "The container repository, used for tagging."
    required: true
  version:
    description: "The version of the image, used for tagging and annotations."
    required: true
  push:
    description: "Whether to push the built image."
    default: "false"
    required: false

runs:
  using: "composite"
  steps:
    - name: Build
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      id: build
      with:
        annotations: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.version=${{ inputs.version }}
        build-args: |
          SERVICE=${{ inputs.service }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        push: ${{ inputs.push }}
        tags: ${{ inputs.repository }}:${{ inputs.version }}
        target: runtime
        # TODO: provenance=max
        # TODO: sbom=true
      env:
        SOURCE_DATE_EPOCH: 0

    - name: Scan
      uses: aquasecurity/trivy-action@dc5a429b52fcf669ce959baa2c2dd26090d2a6c4 # 0.32.0
      with:
        image-ref: ${{ inputs.repository }}:${{ inputs.version }}
        scan-type: image
        trivy-config: trivy.yaml
        format: sarif
        output: trivy-results.sarif

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@51f77329afa6477de8c49fc9c7046c15b9a4e79d # v3.29.5
      with:
        sarif_file: trivy-results.sarif

    - name: Cosign
      shell: bash
      if: inputs.push == 'true'
      run: |
        cosign sign --yes ${repository}:${version}@${digest}
      env:
        repository: ${{ inputs.repository }}
        version: ${{ inputs.version }}
        digest: ${{ steps.build.outputs.digest }}
