---
name: Container Build
description: Build, push, scan and sign a container.

inputs:
  service:
    description: "The service to build, used as a build argument."
    required: true
  repository:
    description: "The container repository, used for tagging."
    required: true
  version:
    description: "The version of the image, used for tagging and annotations."
    required: true
  trivy-version:
    description: "The version of Trivy to install."
    default: ""
    required: false

runs:
  using: "composite"
  steps:
    - name: Build
      uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
      id: build
      with:
        annotations: |
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.version=${{ inputs.version }}
        build-args: |
          SERVICE=${{ inputs.service }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64, linux/arm64
        push: true
        tags: ${{ inputs.repository }}:${{ inputs.version }}
        target: runtime
        provenance: mode=max
        sbom: true
      env:
        SOURCE_DATE_EPOCH: 0

    - name: Scan
      uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
      with:
        image-ref: ${{ inputs.repository }}:${{ inputs.version }}
        scan-type: image
        trivy-config: trivy.yaml
        format: sarif
        output: trivy-results.sarif
        version: ${{ inputs.trivy-version }}

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
      with:
        sarif_file: trivy-results.sarif

    - name: Sign image
      shell: bash
      run: |
        cosign sign --yes ${repository}:${version}@${digest} --verbose
      env:
        repository: ${{ inputs.repository }}
        version: ${{ inputs.version }}
        digest: ${{ steps.build.outputs.digest }}

    - name: Verify signature
      shell: bash
      run: |
        cosign verify \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity="${GITHUB_SERVER_URL}/${GITHUB_WORKFLOW_REF}" \
          ${repository}:${version}@${digest}
      env:
        repository: ${{ inputs.repository }}
        version: ${{ inputs.version }}
        digest: ${{ steps.build.outputs.digest }}
