// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockrepositories

import (
	"context"
	"time"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	mock "github.com/stretchr/testify/mock"
)

// NewAuditEvent creates a new instance of AuditEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditEvent {
	mock := &AuditEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditEvent is an autogenerated mock type for the AuditEvent type
type AuditEvent struct {
	mock.Mock
}

type AuditEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditEvent) EXPECT() *AuditEvent_Expecter {
	return &AuditEvent_Expecter{mock: &_m.Mock}
}

// CreateAuditEvent provides a mock function for the type AuditEvent
func (_mock *AuditEvent) CreateAuditEvent(context1 context.Context, auditEvent *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditEvent_CreateAuditEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditEvent'
type AuditEvent_CreateAuditEvent_Call struct {
	*mock.Call
}

// CreateAuditEvent is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEvent *entities.AuditEvent
func (_e *AuditEvent_Expecter) CreateAuditEvent(context1 interface{}, auditEvent interface{}) *AuditEvent_CreateAuditEvent_Call {
	return &AuditEvent_CreateAuditEvent_Call{Call: _e.mock.On("CreateAuditEvent", context1, auditEvent)}
}

func (_c *AuditEvent_CreateAuditEvent_Call) Run(run func(context1 context.Context, auditEvent *entities.AuditEvent)) *AuditEvent_CreateAuditEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(*entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditEvent_CreateAuditEvent_Call) Return(err error) *AuditEvent_CreateAuditEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditEvent_CreateAuditEvent_Call) RunAndReturn(run func(context1 context.Context, auditEvent *entities.AuditEvent) error) *AuditEvent_CreateAuditEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditEvents provides a mock function for the type AuditEvent
func (_mock *AuditEvent) ListAuditEvents(context1 context.Context) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditEvents")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuditEvent_ListAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditEvents'
type AuditEvent_ListAuditEvents_Call struct {
	*mock.Call
}

// ListAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
func (_e *AuditEvent_Expecter) ListAuditEvents(context1 interface{}) *AuditEvent_ListAuditEvents_Call {
	return &AuditEvent_ListAuditEvents_Call{Call: _e.mock.On("ListAuditEvents", context1)}
}

func (_c *AuditEvent_ListAuditEvents_Call) Run(run func(context1 context.Context)) *AuditEvent_ListAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *AuditEvent_ListAuditEvents_Call) Return(auditEvents []*entities.AuditEvent, err error) *AuditEvent_ListAuditEvents_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *AuditEvent_ListAuditEvents_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.AuditEvent, error)) *AuditEvent_ListAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAuditEvents provides a mock function for the type AuditEvent
func (_mock *AuditEvent) WatchAuditEvents(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEventCh)

	if len(ret) == 0 {
		panic("no return value specified for WatchAuditEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan<- *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEventCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditEvent_WatchAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAuditEvents'
type AuditEvent_WatchAuditEvents_Call struct {
	*mock.Call
}

// WatchAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEventCh chan<- *entities.AuditEvent
func (_e *AuditEvent_Expecter) WatchAuditEvents(context1 interface{}, auditEventCh interface{}) *AuditEvent_WatchAuditEvents_Call {
	return &AuditEvent_WatchAuditEvents_Call{Call: _e.mock.On("WatchAuditEvents", context1, auditEventCh)}
}

func (_c *AuditEvent_WatchAuditEvents_Call) Run(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent)) *AuditEvent_WatchAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(chan<- *entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditEvent_WatchAuditEvents_Call) Return(err error) *AuditEvent_WatchAuditEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditEvent_WatchAuditEvents_Call) RunAndReturn(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error) *AuditEvent_WatchAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewClock creates a new instance of Clock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Clock {
	mock := &Clock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Clock is an autogenerated mock type for the Clock type
type Clock struct {
	mock.Mock
}

type Clock_Expecter struct {
	mock *mock.Mock
}

func (_m *Clock) EXPECT() *Clock_Expecter {
	return &Clock_Expecter{mock: &_m.Mock}
}

// LocalNow provides a mock function for the type Clock
func (_mock *Clock) LocalNow() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LocalNow")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Clock_LocalNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LocalNow'
type Clock_LocalNow_Call struct {
	*mock.Call
}

// LocalNow is a helper method to define mock.On call
func (_e *Clock_Expecter) LocalNow() *Clock_LocalNow_Call {
	return &Clock_LocalNow_Call{Call: _e.mock.On("LocalNow")}
}

func (_c *Clock_LocalNow_Call) Run(run func()) *Clock_LocalNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Clock_LocalNow_Call) Return(time1 time.Time) *Clock_LocalNow_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *Clock_LocalNow_Call) RunAndReturn(run func() time.Time) *Clock_LocalNow_Call {
	_c.Call.Return(run)
	return _c
}

// Since provides a mock function for the type Clock
func (_mock *Clock) Since(t time.Time) time.Duration {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Since")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// Clock_Since_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Since'
type Clock_Since_Call struct {
	*mock.Call
}

// Since is a helper method to define mock.On call
//   - t time.Time
func (_e *Clock_Expecter) Since(t interface{}) *Clock_Since_Call {
	return &Clock_Since_Call{Call: _e.mock.On("Since", t)}
}

func (_c *Clock_Since_Call) Run(run func(t time.Time)) *Clock_Since_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Clock_Since_Call) Return(duration time.Duration) *Clock_Since_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *Clock_Since_Call) RunAndReturn(run func(t time.Time) time.Duration) *Clock_Since_Call {
	_c.Call.Return(run)
	return _c
}

// UTCNow provides a mock function for the type Clock
func (_mock *Clock) UTCNow() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UTCNow")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Clock_UTCNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UTCNow'
type Clock_UTCNow_Call struct {
	*mock.Call
}

// UTCNow is a helper method to define mock.On call
func (_e *Clock_Expecter) UTCNow() *Clock_UTCNow_Call {
	return &Clock_UTCNow_Call{Call: _e.mock.On("UTCNow")}
}

func (_c *Clock_UTCNow_Call) Run(run func()) *Clock_UTCNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Clock_UTCNow_Call) Return(time1 time.Time) *Clock_UTCNow_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *Clock_UTCNow_Call) RunAndReturn(run func() time.Time) *Clock_UTCNow_Call {
	_c.Call.Return(run)
	return _c
}

// Until provides a mock function for the type Clock
func (_mock *Clock) Until(t time.Time) time.Duration {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Until")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// Clock_Until_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Until'
type Clock_Until_Call struct {
	*mock.Call
}

// Until is a helper method to define mock.On call
//   - t time.Time
func (_e *Clock_Expecter) Until(t interface{}) *Clock_Until_Call {
	return &Clock_Until_Call{Call: _e.mock.On("Until", t)}
}

func (_c *Clock_Until_Call) Run(run func(t time.Time)) *Clock_Until_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Clock_Until_Call) Return(duration time.Duration) *Clock_Until_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *Clock_Until_Call) RunAndReturn(run func(t time.Time) time.Duration) *Clock_Until_Call {
	_c.Call.Return(run)
	return _c
}

// NewResource creates a new instance of Resource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *Resource {
	mock := &Resource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Resource is an autogenerated mock type for the Resource type
type Resource struct {
	mock.Mock
}

type Resource_Expecter struct {
	mock *mock.Mock
}

func (_m *Resource) EXPECT() *Resource_Expecter {
	return &Resource_Expecter{mock: &_m.Mock}
}

// CreateResource provides a mock function for the type Resource
func (_mock *Resource) CreateResource(context1 context.Context, resource *entities.Resource) error {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) error); ok {
		r0 = returnFunc(context1, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Resource_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type Resource_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *Resource_Expecter) CreateResource(context1 interface{}, resource interface{}) *Resource_CreateResource_Call {
	return &Resource_CreateResource_Call{Call: _e.mock.On("CreateResource", context1, resource)}
}

func (_c *Resource_CreateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *Resource_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resource_CreateResource_Call) Return(err error) *Resource_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Resource_CreateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) error) *Resource_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type Resource
func (_mock *Resource) DeleteResource(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Resource_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type Resource_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *Resource_Expecter) DeleteResource(context1 interface{}, uUID interface{}) *Resource_DeleteResource_Call {
	return &Resource_DeleteResource_Call{Call: _e.mock.On("DeleteResource", context1, uUID)}
}

func (_c *Resource_DeleteResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *Resource_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resource_DeleteResource_Call) Return(err error) *Resource_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Resource_DeleteResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *Resource_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type Resource
func (_mock *Resource) GetResource(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resource_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type Resource_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *Resource_Expecter) GetResource(context1 interface{}, uUID interface{}) *Resource_GetResource_Call {
	return &Resource_GetResource_Call{Call: _e.mock.On("GetResource", context1, uUID)}
}

func (_c *Resource_GetResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *Resource_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resource_GetResource_Call) Return(resource *entities.Resource, err error) *Resource_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *Resource_GetResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error)) *Resource_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type Resource
func (_mock *Resource) ListResources(context1 context.Context) ([]*entities.Resource, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 []*entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.Resource, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.Resource); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resource_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type Resource_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - context1 context.Context
func (_e *Resource_Expecter) ListResources(context1 interface{}) *Resource_ListResources_Call {
	return &Resource_ListResources_Call{Call: _e.mock.On("ListResources", context1)}
}

func (_c *Resource_ListResources_Call) Run(run func(context1 context.Context)) *Resource_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Resource_ListResources_Call) Return(resources []*entities.Resource, err error) *Resource_ListResources_Call {
	_c.Call.Return(resources, err)
	return _c
}

func (_c *Resource_ListResources_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.Resource, error)) *Resource_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type Resource
func (_mock *Resource) UpdateResource(context1 context.Context, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Resource) error); ok {
		r1 = returnFunc(context1, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Resource_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type Resource_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *Resource_Expecter) UpdateResource(context1 interface{}, resource interface{}) *Resource_UpdateResource_Call {
	return &Resource_UpdateResource_Call{Call: _e.mock.On("UpdateResource", context1, resource)}
}

func (_c *Resource_UpdateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *Resource_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Resource_UpdateResource_Call) Return(resource1 *entities.Resource, err error) *Resource_UpdateResource_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *Resource_UpdateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) (*entities.Resource, error)) *Resource_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// NewUUIDGenerator creates a new instance of UUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *UUIDGenerator {
	mock := &UUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UUIDGenerator is an autogenerated mock type for the UUIDGenerator type
type UUIDGenerator struct {
	mock.Mock
}

type UUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *UUIDGenerator) EXPECT() *UUIDGenerator_Expecter {
	return &UUIDGenerator_Expecter{mock: &_m.Mock}
}

// NewV4 provides a mock function for the type UUIDGenerator
func (_mock *UUIDGenerator) NewV4() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewV4")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UUIDGenerator_NewV4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewV4'
type UUIDGenerator_NewV4_Call struct {
	*mock.Call
}

// NewV4 is a helper method to define mock.On call
func (_e *UUIDGenerator_Expecter) NewV4() *UUIDGenerator_NewV4_Call {
	return &UUIDGenerator_NewV4_Call{Call: _e.mock.On("NewV4")}
}

func (_c *UUIDGenerator_NewV4_Call) Run(run func()) *UUIDGenerator_NewV4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UUIDGenerator_NewV4_Call) Return(uUID uuid.UUID, err error) *UUIDGenerator_NewV4_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *UUIDGenerator_NewV4_Call) RunAndReturn(run func() (uuid.UUID, error)) *UUIDGenerator_NewV4_Call {
	_c.Call.Return(run)
	return _c
}

// NewV7 provides a mock function for the type UUIDGenerator
func (_mock *UUIDGenerator) NewV7() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewV7")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UUIDGenerator_NewV7_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewV7'
type UUIDGenerator_NewV7_Call struct {
	*mock.Call
}

// NewV7 is a helper method to define mock.On call
func (_e *UUIDGenerator_Expecter) NewV7() *UUIDGenerator_NewV7_Call {
	return &UUIDGenerator_NewV7_Call{Call: _e.mock.On("NewV7")}
}

func (_c *UUIDGenerator_NewV7_Call) Run(run func()) *UUIDGenerator_NewV7_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UUIDGenerator_NewV7_Call) Return(uUID uuid.UUID, err error) *UUIDGenerator_NewV7_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *UUIDGenerator_NewV7_Call) RunAndReturn(run func() (uuid.UUID, error)) *UUIDGenerator_NewV7_Call {
	_c.Call.Return(run)
	return _c
}
