// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package usecasefacades

import (
	"context"
	"log/slog"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	"github.com/mattdowdell/sandbox/internal/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResourceCreator creates a new instance of MockResourceCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceCreator {
	mock := &MockResourceCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceCreator is an autogenerated mock type for the ResourceCreator type
type MockResourceCreator struct {
	mock.Mock
}

type MockResourceCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceCreator) EXPECT() *MockResourceCreator_Expecter {
	return &MockResourceCreator_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockResourceCreator
func (_mock *MockResourceCreator) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, resource1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, resource1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, resource1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource, resource1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceCreator_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResourceCreator_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - resource1 *entities.Resource
func (_e *MockResourceCreator_Expecter) Execute(context1 any, logger any, resource any, resource1 any) *MockResourceCreator_Execute_Call {
	return &MockResourceCreator_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, resource1)}
}

func (_c *MockResourceCreator_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource)) *MockResourceCreator_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 *entities.Resource
		if args[3] != nil {
			arg3 = args[3].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResourceCreator_Execute_Call) Return(resource2 *entities.Resource, err error) *MockResourceCreator_Execute_Call {
	_c.Call.Return(resource2, err)
	return _c
}

func (_c *MockResourceCreator_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error)) *MockResourceCreator_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceGetter creates a new instance of MockResourceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceGetter {
	mock := &MockResourceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceGetter is an autogenerated mock type for the ResourceGetter type
type MockResourceGetter struct {
	mock.Mock
}

type MockResourceGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceGetter) EXPECT() *MockResourceGetter_Expecter {
	return &MockResourceGetter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockResourceGetter
func (_mock *MockResourceGetter) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) error); ok {
		r1 = returnFunc(context1, logger, resource, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceGetter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResourceGetter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - uUID uuid.UUID
func (_e *MockResourceGetter_Expecter) Execute(context1 any, logger any, resource any, uUID any) *MockResourceGetter_Execute_Call {
	return &MockResourceGetter_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, uUID)}
}

func (_c *MockResourceGetter_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID)) *MockResourceGetter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResourceGetter_Execute_Call) Return(resource1 *entities.Resource, err error) *MockResourceGetter_Execute_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *MockResourceGetter_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) (*entities.Resource, error)) *MockResourceGetter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceLister creates a new instance of MockResourceLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceLister {
	mock := &MockResourceLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceLister is an autogenerated mock type for the ResourceLister type
type MockResourceLister struct {
	mock.Mock
}

type MockResourceLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceLister) EXPECT() *MockResourceLister_Expecter {
	return &MockResourceLister_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockResourceLister
func (_mock *MockResourceLister) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error) {
	ret := _mock.Called(context1, logger, resource, pager)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *repositories.Paged[*entities.Resource]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, repositories.Pager) (*repositories.Paged[*entities.Resource], error)); ok {
		return returnFunc(context1, logger, resource, pager)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, repositories.Pager) *repositories.Paged[*entities.Resource]); ok {
		r0 = returnFunc(context1, logger, resource, pager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.Paged[*entities.Resource])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, repositories.Pager) error); ok {
		r1 = returnFunc(context1, logger, resource, pager)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceLister_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResourceLister_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - pager repositories.Pager
func (_e *MockResourceLister_Expecter) Execute(context1 any, logger any, resource any, pager any) *MockResourceLister_Execute_Call {
	return &MockResourceLister_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, pager)}
}

func (_c *MockResourceLister_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, pager repositories.Pager)) *MockResourceLister_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 repositories.Pager
		if args[3] != nil {
			arg3 = args[3].(repositories.Pager)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResourceLister_Execute_Call) Return(paged *repositories.Paged[*entities.Resource], err error) *MockResourceLister_Execute_Call {
	_c.Call.Return(paged, err)
	return _c
}

func (_c *MockResourceLister_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error)) *MockResourceLister_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceUpdater creates a new instance of MockResourceUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceUpdater {
	mock := &MockResourceUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceUpdater is an autogenerated mock type for the ResourceUpdater type
type MockResourceUpdater struct {
	mock.Mock
}

type MockResourceUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceUpdater) EXPECT() *MockResourceUpdater_Expecter {
	return &MockResourceUpdater_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockResourceUpdater
func (_mock *MockResourceUpdater) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, logger, resource, resource1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, logger, resource, resource1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, logger, resource, resource1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.Resource, *entities.Resource) error); ok {
		r1 = returnFunc(context1, logger, resource, resource1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResourceUpdater_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResourceUpdater_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - resource1 *entities.Resource
func (_e *MockResourceUpdater_Expecter) Execute(context1 any, logger any, resource any, resource1 any) *MockResourceUpdater_Execute_Call {
	return &MockResourceUpdater_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, resource1)}
}

func (_c *MockResourceUpdater_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource)) *MockResourceUpdater_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 *entities.Resource
		if args[3] != nil {
			arg3 = args[3].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResourceUpdater_Execute_Call) Return(resource2 *entities.Resource, err error) *MockResourceUpdater_Execute_Call {
	_c.Call.Return(resource2, err)
	return _c
}

func (_c *MockResourceUpdater_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, resource1 *entities.Resource) (*entities.Resource, error)) *MockResourceUpdater_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResourceDeleter creates a new instance of MockResourceDeleter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResourceDeleter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResourceDeleter {
	mock := &MockResourceDeleter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResourceDeleter is an autogenerated mock type for the ResourceDeleter type
type MockResourceDeleter struct {
	mock.Mock
}

type MockResourceDeleter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResourceDeleter) EXPECT() *MockResourceDeleter_Expecter {
	return &MockResourceDeleter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockResourceDeleter
func (_mock *MockResourceDeleter) Execute(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) error {
	ret := _mock.Called(context1, logger, resource, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.Resource, uuid.UUID) error); ok {
		r0 = returnFunc(context1, logger, resource, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResourceDeleter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockResourceDeleter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - resource repositories.Resource
//   - uUID uuid.UUID
func (_e *MockResourceDeleter_Expecter) Execute(context1 any, logger any, resource any, uUID any) *MockResourceDeleter_Execute_Call {
	return &MockResourceDeleter_Execute_Call{Call: _e.mock.On("Execute", context1, logger, resource, uUID)}
}

func (_c *MockResourceDeleter_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID)) *MockResourceDeleter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.Resource
		if args[2] != nil {
			arg2 = args[2].(repositories.Resource)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResourceDeleter_Execute_Call) Return(err error) *MockResourceDeleter_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResourceDeleter_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, resource repositories.Resource, uUID uuid.UUID) error) *MockResourceDeleter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditEventLister creates a new instance of MockAuditEventLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEventLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEventLister {
	mock := &MockAuditEventLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditEventLister is an autogenerated mock type for the AuditEventLister type
type MockAuditEventLister struct {
	mock.Mock
}

type MockAuditEventLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditEventLister) EXPECT() *MockAuditEventLister_Expecter {
	return &MockAuditEventLister_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAuditEventLister
func (_mock *MockAuditEventLister) Execute(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1, logger, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1, logger, auditEvent)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger, auditEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *slog.Logger, repositories.AuditEvent) error); ok {
		r1 = returnFunc(context1, logger, auditEvent)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditEventLister_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAuditEventLister_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - auditEvent repositories.AuditEvent
func (_e *MockAuditEventLister_Expecter) Execute(context1 any, logger any, auditEvent any) *MockAuditEventLister_Execute_Call {
	return &MockAuditEventLister_Execute_Call{Call: _e.mock.On("Execute", context1, logger, auditEvent)}
}

func (_c *MockAuditEventLister_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent)) *MockAuditEventLister_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.AuditEvent
		if args[2] != nil {
			arg2 = args[2].(repositories.AuditEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditEventLister_Execute_Call) Return(auditEvents []*entities.AuditEvent, err error) *MockAuditEventLister_Execute_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *MockAuditEventLister_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) ([]*entities.AuditEvent, error)) *MockAuditEventLister_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditEventWatcher creates a new instance of MockAuditEventWatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEventWatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEventWatcher {
	mock := &MockAuditEventWatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditEventWatcher is an autogenerated mock type for the AuditEventWatcher type
type MockAuditEventWatcher struct {
	mock.Mock
}

type MockAuditEventWatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditEventWatcher) EXPECT() *MockAuditEventWatcher_Expecter {
	return &MockAuditEventWatcher_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAuditEventWatcher
func (_mock *MockAuditEventWatcher) Execute(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) <-chan *entities.AuditEvent {
	ret := _mock.Called(context1, logger, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 <-chan *entities.AuditEvent
	if returnFunc, ok := ret.Get(0).(func(context.Context, *slog.Logger, repositories.AuditEvent) <-chan *entities.AuditEvent); ok {
		r0 = returnFunc(context1, logger, auditEvent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *entities.AuditEvent)
		}
	}
	return r0
}

// MockAuditEventWatcher_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAuditEventWatcher_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - context1 context.Context
//   - logger *slog.Logger
//   - auditEvent repositories.AuditEvent
func (_e *MockAuditEventWatcher_Expecter) Execute(context1 any, logger any, auditEvent any) *MockAuditEventWatcher_Execute_Call {
	return &MockAuditEventWatcher_Execute_Call{Call: _e.mock.On("Execute", context1, logger, auditEvent)}
}

func (_c *MockAuditEventWatcher_Execute_Call) Run(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent)) *MockAuditEventWatcher_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *slog.Logger
		if args[1] != nil {
			arg1 = args[1].(*slog.Logger)
		}
		var arg2 repositories.AuditEvent
		if args[2] != nil {
			arg2 = args[2].(repositories.AuditEvent)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuditEventWatcher_Execute_Call) Return(auditEventCh <-chan *entities.AuditEvent) *MockAuditEventWatcher_Execute_Call {
	_c.Call.Return(auditEventCh)
	return _c
}

func (_c *MockAuditEventWatcher_Execute_Call) RunAndReturn(run func(context1 context.Context, logger *slog.Logger, auditEvent repositories.AuditEvent) <-chan *entities.AuditEvent) *MockAuditEventWatcher_Execute_Call {
	_c.Call.Return(run)
	return _c
}
