// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package slogt

import (
	"io"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTB creates a new instance of MockTB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTB {
	mock := &MockTB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTB is an autogenerated mock type for the TB type
type MockTB struct {
	mock.Mock
}

type MockTB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTB) EXPECT() *MockTB_Expecter {
	return &MockTB_Expecter{mock: &_m.Mock}
}

// Helper provides a mock function for the type MockTB
func (_mock *MockTB) Helper() {
	_mock.Called()
	return
}

// MockTB_Helper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Helper'
type MockTB_Helper_Call struct {
	*mock.Call
}

// Helper is a helper method to define mock.On call
func (_e *MockTB_Expecter) Helper() *MockTB_Helper_Call {
	return &MockTB_Helper_Call{Call: _e.mock.On("Helper")}
}

func (_c *MockTB_Helper_Call) Run(run func()) *MockTB_Helper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTB_Helper_Call) Return() *MockTB_Helper_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTB_Helper_Call) RunAndReturn(run func()) *MockTB_Helper_Call {
	_c.Run(run)
	return _c
}

// Output provides a mock function for the type MockTB
func (_mock *MockTB) Output() io.Writer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 io.Writer
	if returnFunc, ok := ret.Get(0).(func() io.Writer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}
	return r0
}

// MockTB_Output_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Output'
type MockTB_Output_Call struct {
	*mock.Call
}

// Output is a helper method to define mock.On call
func (_e *MockTB_Expecter) Output() *MockTB_Output_Call {
	return &MockTB_Output_Call{Call: _e.mock.On("Output")}
}

func (_c *MockTB_Output_Call) Run(run func()) *MockTB_Output_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTB_Output_Call) Return(writer io.Writer) *MockTB_Output_Call {
	_c.Call.Return(writer)
	return _c
}

func (_c *MockTB_Output_Call) RunAndReturn(run func() io.Writer) *MockTB_Output_Call {
	_c.Call.Return(run)
	return _c
}
