package authn_test

// This is a copy of:
//
//	- https://github.com/mattdowdell/sandbox/blob/b55197b560f26c783f781364cceed10978c9cbc0/mocks/external/connectrpc.com/mockconnect/unary_func.go
//	- https://github.com/mattdowdell/sandbox/blob/b55197b560f26c783f781364cceed10978c9cbc0/mocks/external/connectrpc.com/mockconnect/streaming_handler_func.go
//
// Mockery v3 dropped support for function mocks.
// For further discussion, see https://github.com/vektra/mockery/discussions/1091

import (
	context "context"

	connect "connectrpc.com/connect"
	mock "github.com/stretchr/testify/mock"
)

// UnaryFunc is an autogenerated mock type for the UnaryFunc type
type UnaryFunc struct {
	mock.Mock
}

type UnaryFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *UnaryFunc) EXPECT() *UnaryFunc_Expecter {
	return &UnaryFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *UnaryFunc) Execute(_a0 context.Context, _a1 connect.AnyRequest) (connect.AnyResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 connect.AnyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, connect.AnyRequest) (connect.AnyResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, connect.AnyRequest) connect.AnyResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(connect.AnyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, connect.AnyRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnaryFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UnaryFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 connect.AnyRequest
func (_e *UnaryFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *UnaryFunc_Execute_Call {
	return &UnaryFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *UnaryFunc_Execute_Call) Run(run func(_a0 context.Context, _a1 connect.AnyRequest)) *UnaryFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(connect.AnyRequest))
	})
	return _c
}

func (_c *UnaryFunc_Execute_Call) Return(_a0 connect.AnyResponse, _a1 error) *UnaryFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UnaryFunc_Execute_Call) RunAndReturn(run func(context.Context, connect.AnyRequest) (connect.AnyResponse, error)) *UnaryFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnaryFunc creates a new instance of UnaryFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnaryFunc(t interface {
	mock.TestingT
	Cleanup(func())
},
) *UnaryFunc {
	mock := &UnaryFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StreamingHandlerFunc is an autogenerated mock type for the StreamingHandlerFunc type
type StreamingHandlerFunc struct {
	mock.Mock
}

type StreamingHandlerFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *StreamingHandlerFunc) EXPECT() *StreamingHandlerFunc_Expecter {
	return &StreamingHandlerFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *StreamingHandlerFunc) Execute(_a0 context.Context, _a1 connect.StreamingHandlerConn) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, connect.StreamingHandlerConn) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamingHandlerFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type StreamingHandlerFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 connect.StreamingHandlerConn
func (_e *StreamingHandlerFunc_Expecter) Execute(_a0 interface{}, _a1 interface{}) *StreamingHandlerFunc_Execute_Call {
	return &StreamingHandlerFunc_Execute_Call{Call: _e.mock.On("Execute", _a0, _a1)}
}

func (_c *StreamingHandlerFunc_Execute_Call) Run(run func(_a0 context.Context, _a1 connect.StreamingHandlerConn)) *StreamingHandlerFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(connect.StreamingHandlerConn))
	})
	return _c
}

func (_c *StreamingHandlerFunc_Execute_Call) Return(_a0 error) *StreamingHandlerFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamingHandlerFunc_Execute_Call) RunAndReturn(run func(context.Context, connect.StreamingHandlerConn) error) *StreamingHandlerFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreamingHandlerFunc creates a new instance of StreamingHandlerFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamingHandlerFunc(t interface {
	mock.TestingT
	Cleanup(func())
},
) *StreamingHandlerFunc {
	mock := &StreamingHandlerFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
