#! /usr/bin/env bash

set -eu -o pipefail

tools=`bingo list | tail -n+3 | awk '{print $1}'`

echo "# Generated by ./tools/bingo-justfile.sh. DO NOT EDIT."
echo
echo 'gopath := shell("go env GOPATH")'
echo

for tool in $tools
do
	if [[ "$tool" == protoc-gen-* ]]
	then
		filename=`bingo list | awk '{print $1 " " $2}' | grep "\b${tool}\b" | awk '{print $1}'`
		echo "${tool} := join(gopath, \"bin\", \"$filename\")"
	else
		filename=`bingo list | awk '{print $1 " " $2 }' | grep "\b${tool}\b" | awk '{print $2}'`
		echo "${tool} := join(gopath, \"bin\", \"$filename\")"
	fi

	echo
	echo "[private]"
	echo "install-${tool}:"

	# use symlink for protoc plugins
	# avoids needing to maintain versions in buf.gen.yaml
	if [[ "$tool" == protoc-gen-* ]]
	then
		echo "    {{ if path_exists(${tool}) == \"true\" { \"\" } else { \"bingo get ${tool} -l\" } }}"
	else
		echo "    {{ if path_exists(${tool}) == \"true\" { \"\" } else { \"bingo get ${tool}\" } }}"
	fi

	echo
done
