#! /usr/bin/env bash

set -eu -o pipefail

tools=`bingo list | tail -n+3 | awk '{print $1}'`

echo "# Generated by ./tools/bingo-justfile.sh. DO NOT EDIT."
echo
echo 'gopath := shell("go env GOPATH")'
echo

for tool in $tools
do
	filename=`bingo list | grep $tool | awk '{print $2}'`

	echo "${tool} := join(gopath, \"bin\", \"$filename\")"
	echo
	echo "[private]"
	echo "@install-${tool}:"
	echo "    bingo get ${tool}"
	echo
done
