#! /usr/bin/env bash

set -eu -o pipefail

protoc_gen_go=`bingo list | grep "^protoc-gen-go\b" | awk '{print $2}'`
protoc_gen_connect_go=`bingo list | grep "^protoc-gen-connect-go\b" | awk '{print $2}'`

echo "---"
echo "# https://buf.build/docs/configuration/v2/buf-gen-yaml/"
echo "# Generated by ./tools/regen-buf-gen.sh. DO NOT EDIT."
echo
echo "version: v2"
echo "plugins:"
echo "  - local: ${protoc_gen_go}"
echo "    out: gen"
echo "    opt: paths=source_relative"
echo "  - local: ${protoc_gen_connect_go}"
echo "    out: gen"
echo "    opt: paths=source_relative"
