// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mockrepositories

import (
	"context"
	"time"

	"github.com/gofrs/uuid/v5"
	"github.com/mattdowdell/sandbox/internal/domain/entities"
	"github.com/mattdowdell/sandbox/internal/domain/repositories"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuditEvent creates a new instance of MockAuditEvent. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditEvent(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditEvent {
	mock := &MockAuditEvent{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuditEvent is an autogenerated mock type for the AuditEvent type
type MockAuditEvent struct {
	mock.Mock
}

type MockAuditEvent_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditEvent) EXPECT() *MockAuditEvent_Expecter {
	return &MockAuditEvent_Expecter{mock: &_m.Mock}
}

// CreateAuditEvent provides a mock function for the type MockAuditEvent
func (_mock *MockAuditEvent) CreateAuditEvent(context1 context.Context, auditEvent *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEvent)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditEvent_CreateAuditEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditEvent'
type MockAuditEvent_CreateAuditEvent_Call struct {
	*mock.Call
}

// CreateAuditEvent is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEvent *entities.AuditEvent
func (_e *MockAuditEvent_Expecter) CreateAuditEvent(context1 any, auditEvent any) *MockAuditEvent_CreateAuditEvent_Call {
	return &MockAuditEvent_CreateAuditEvent_Call{Call: _e.mock.On("CreateAuditEvent", context1, auditEvent)}
}

func (_c *MockAuditEvent_CreateAuditEvent_Call) Run(run func(context1 context.Context, auditEvent *entities.AuditEvent)) *MockAuditEvent_CreateAuditEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(*entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditEvent_CreateAuditEvent_Call) Return(err error) *MockAuditEvent_CreateAuditEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditEvent_CreateAuditEvent_Call) RunAndReturn(run func(context1 context.Context, auditEvent *entities.AuditEvent) error) *MockAuditEvent_CreateAuditEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ListAuditEvents provides a mock function for the type MockAuditEvent
func (_mock *MockAuditEvent) ListAuditEvents(context1 context.Context) ([]*entities.AuditEvent, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for ListAuditEvents")
	}

	var r0 []*entities.AuditEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*entities.AuditEvent, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*entities.AuditEvent); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entities.AuditEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuditEvent_ListAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAuditEvents'
type MockAuditEvent_ListAuditEvents_Call struct {
	*mock.Call
}

// ListAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockAuditEvent_Expecter) ListAuditEvents(context1 any) *MockAuditEvent_ListAuditEvents_Call {
	return &MockAuditEvent_ListAuditEvents_Call{Call: _e.mock.On("ListAuditEvents", context1)}
}

func (_c *MockAuditEvent_ListAuditEvents_Call) Run(run func(context1 context.Context)) *MockAuditEvent_ListAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuditEvent_ListAuditEvents_Call) Return(auditEvents []*entities.AuditEvent, err error) *MockAuditEvent_ListAuditEvents_Call {
	_c.Call.Return(auditEvents, err)
	return _c
}

func (_c *MockAuditEvent_ListAuditEvents_Call) RunAndReturn(run func(context1 context.Context) ([]*entities.AuditEvent, error)) *MockAuditEvent_ListAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// WatchAuditEvents provides a mock function for the type MockAuditEvent
func (_mock *MockAuditEvent) WatchAuditEvents(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error {
	ret := _mock.Called(context1, auditEventCh)

	if len(ret) == 0 {
		panic("no return value specified for WatchAuditEvents")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, chan<- *entities.AuditEvent) error); ok {
		r0 = returnFunc(context1, auditEventCh)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAuditEvent_WatchAuditEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchAuditEvents'
type MockAuditEvent_WatchAuditEvents_Call struct {
	*mock.Call
}

// WatchAuditEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - auditEventCh chan<- *entities.AuditEvent
func (_e *MockAuditEvent_Expecter) WatchAuditEvents(context1 any, auditEventCh any) *MockAuditEvent_WatchAuditEvents_Call {
	return &MockAuditEvent_WatchAuditEvents_Call{Call: _e.mock.On("WatchAuditEvents", context1, auditEventCh)}
}

func (_c *MockAuditEvent_WatchAuditEvents_Call) Run(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent)) *MockAuditEvent_WatchAuditEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 chan<- *entities.AuditEvent
		if args[1] != nil {
			arg1 = args[1].(chan<- *entities.AuditEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuditEvent_WatchAuditEvents_Call) Return(err error) *MockAuditEvent_WatchAuditEvents_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAuditEvent_WatchAuditEvents_Call) RunAndReturn(run func(context1 context.Context, auditEventCh chan<- *entities.AuditEvent) error) *MockAuditEvent_WatchAuditEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClock creates a new instance of MockClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClock {
	mock := &MockClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClock is an autogenerated mock type for the Clock type
type MockClock struct {
	mock.Mock
}

type MockClock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClock) EXPECT() *MockClock_Expecter {
	return &MockClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function for the type MockClock
func (_mock *MockClock) Now() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Now")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type MockClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *MockClock_Expecter) Now() *MockClock_Now_Call {
	return &MockClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *MockClock_Now_Call) Run(run func()) *MockClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_Now_Call) Return(time1 time.Time) *MockClock_Now_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_Now_Call) RunAndReturn(run func() time.Time) *MockClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

// Since provides a mock function for the type MockClock
func (_mock *MockClock) Since(t time.Time) time.Duration {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Since")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockClock_Since_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Since'
type MockClock_Since_Call struct {
	*mock.Call
}

// Since is a helper method to define mock.On call
//   - t time.Time
func (_e *MockClock_Expecter) Since(t any) *MockClock_Since_Call {
	return &MockClock_Since_Call{Call: _e.mock.On("Since", t)}
}

func (_c *MockClock_Since_Call) Run(run func(t time.Time)) *MockClock_Since_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_Since_Call) Return(duration time.Duration) *MockClock_Since_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockClock_Since_Call) RunAndReturn(run func(t time.Time) time.Duration) *MockClock_Since_Call {
	_c.Call.Return(run)
	return _c
}

// UTCNow provides a mock function for the type MockClock
func (_mock *MockClock) UTCNow() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UTCNow")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockClock_UTCNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UTCNow'
type MockClock_UTCNow_Call struct {
	*mock.Call
}

// UTCNow is a helper method to define mock.On call
func (_e *MockClock_Expecter) UTCNow() *MockClock_UTCNow_Call {
	return &MockClock_UTCNow_Call{Call: _e.mock.On("UTCNow")}
}

func (_c *MockClock_UTCNow_Call) Run(run func()) *MockClock_UTCNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClock_UTCNow_Call) Return(time1 time.Time) *MockClock_UTCNow_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockClock_UTCNow_Call) RunAndReturn(run func() time.Time) *MockClock_UTCNow_Call {
	_c.Call.Return(run)
	return _c
}

// Until provides a mock function for the type MockClock
func (_mock *MockClock) Until(t time.Time) time.Duration {
	ret := _mock.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Until")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func(time.Time) time.Duration); ok {
		r0 = returnFunc(t)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockClock_Until_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Until'
type MockClock_Until_Call struct {
	*mock.Call
}

// Until is a helper method to define mock.On call
//   - t time.Time
func (_e *MockClock_Expecter) Until(t any) *MockClock_Until_Call {
	return &MockClock_Until_Call{Call: _e.mock.On("Until", t)}
}

func (_c *MockClock_Until_Call) Run(run func(t time.Time)) *MockClock_Until_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClock_Until_Call) Return(duration time.Duration) *MockClock_Until_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockClock_Until_Call) RunAndReturn(run func(t time.Time) time.Duration) *MockClock_Until_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResource creates a new instance of MockResource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResource {
	mock := &MockResource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResource is an autogenerated mock type for the Resource type
type MockResource struct {
	mock.Mock
}

type MockResource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResource) EXPECT() *MockResource_Expecter {
	return &MockResource_Expecter{mock: &_m.Mock}
}

// CreateResource provides a mock function for the type MockResource
func (_mock *MockResource) CreateResource(context1 context.Context, resource *entities.Resource) error {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) error); ok {
		r0 = returnFunc(context1, resource)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResource_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type MockResource_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *MockResource_Expecter) CreateResource(context1 any, resource any) *MockResource_CreateResource_Call {
	return &MockResource_CreateResource_Call{Call: _e.mock.On("CreateResource", context1, resource)}
}

func (_c *MockResource_CreateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *MockResource_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResource_CreateResource_Call) Return(err error) *MockResource_CreateResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResource_CreateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) error) *MockResource_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type MockResource
func (_mock *MockResource) DeleteResource(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResource_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type MockResource_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockResource_Expecter) DeleteResource(context1 any, uUID any) *MockResource_DeleteResource_Call {
	return &MockResource_DeleteResource_Call{Call: _e.mock.On("DeleteResource", context1, uUID)}
}

func (_c *MockResource_DeleteResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockResource_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResource_DeleteResource_Call) Return(err error) *MockResource_DeleteResource_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResource_DeleteResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockResource_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type MockResource
func (_mock *MockResource) GetResource(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entities.Resource, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entities.Resource); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResource_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type MockResource_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockResource_Expecter) GetResource(context1 any, uUID any) *MockResource_GetResource_Call {
	return &MockResource_GetResource_Call{Call: _e.mock.On("GetResource", context1, uUID)}
}

func (_c *MockResource_GetResource_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockResource_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResource_GetResource_Call) Return(resource *entities.Resource, err error) *MockResource_GetResource_Call {
	_c.Call.Return(resource, err)
	return _c
}

func (_c *MockResource_GetResource_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*entities.Resource, error)) *MockResource_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function for the type MockResource
func (_mock *MockResource) ListResources(context1 context.Context, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error) {
	ret := _mock.Called(context1, pager)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 *repositories.Paged[*entities.Resource]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.Pager) (*repositories.Paged[*entities.Resource], error)); ok {
		return returnFunc(context1, pager)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repositories.Pager) *repositories.Paged[*entities.Resource]); ok {
		r0 = returnFunc(context1, pager)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repositories.Paged[*entities.Resource])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repositories.Pager) error); ok {
		r1 = returnFunc(context1, pager)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResource_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockResource_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - context1 context.Context
//   - pager repositories.Pager
func (_e *MockResource_Expecter) ListResources(context1 any, pager any) *MockResource_ListResources_Call {
	return &MockResource_ListResources_Call{Call: _e.mock.On("ListResources", context1, pager)}
}

func (_c *MockResource_ListResources_Call) Run(run func(context1 context.Context, pager repositories.Pager)) *MockResource_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repositories.Pager
		if args[1] != nil {
			arg1 = args[1].(repositories.Pager)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResource_ListResources_Call) Return(paged *repositories.Paged[*entities.Resource], err error) *MockResource_ListResources_Call {
	_c.Call.Return(paged, err)
	return _c
}

func (_c *MockResource_ListResources_Call) RunAndReturn(run func(context1 context.Context, pager repositories.Pager) (*repositories.Paged[*entities.Resource], error)) *MockResource_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function for the type MockResource
func (_mock *MockResource) UpdateResource(context1 context.Context, resource *entities.Resource) (*entities.Resource, error) {
	ret := _mock.Called(context1, resource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *entities.Resource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) (*entities.Resource, error)); ok {
		return returnFunc(context1, resource)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.Resource) *entities.Resource); ok {
		r0 = returnFunc(context1, resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.Resource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.Resource) error); ok {
		r1 = returnFunc(context1, resource)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResource_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type MockResource_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - context1 context.Context
//   - resource *entities.Resource
func (_e *MockResource_Expecter) UpdateResource(context1 any, resource any) *MockResource_UpdateResource_Call {
	return &MockResource_UpdateResource_Call{Call: _e.mock.On("UpdateResource", context1, resource)}
}

func (_c *MockResource_UpdateResource_Call) Run(run func(context1 context.Context, resource *entities.Resource)) *MockResource_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *entities.Resource
		if args[1] != nil {
			arg1 = args[1].(*entities.Resource)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResource_UpdateResource_Call) Return(resource1 *entities.Resource, err error) *MockResource_UpdateResource_Call {
	_c.Call.Return(resource1, err)
	return _c
}

func (_c *MockResource_UpdateResource_Call) RunAndReturn(run func(context1 context.Context, resource *entities.Resource) (*entities.Resource, error)) *MockResource_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUUIDGenerator creates a new instance of MockUUIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUUIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUUIDGenerator {
	mock := &MockUUIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUUIDGenerator is an autogenerated mock type for the UUIDGenerator type
type MockUUIDGenerator struct {
	mock.Mock
}

type MockUUIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUUIDGenerator) EXPECT() *MockUUIDGenerator_Expecter {
	return &MockUUIDGenerator_Expecter{mock: &_m.Mock}
}

// NewV4 provides a mock function for the type MockUUIDGenerator
func (_mock *MockUUIDGenerator) NewV4() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewV4")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUUIDGenerator_NewV4_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewV4'
type MockUUIDGenerator_NewV4_Call struct {
	*mock.Call
}

// NewV4 is a helper method to define mock.On call
func (_e *MockUUIDGenerator_Expecter) NewV4() *MockUUIDGenerator_NewV4_Call {
	return &MockUUIDGenerator_NewV4_Call{Call: _e.mock.On("NewV4")}
}

func (_c *MockUUIDGenerator_NewV4_Call) Run(run func()) *MockUUIDGenerator_NewV4_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUIDGenerator_NewV4_Call) Return(uUID uuid.UUID, err error) *MockUUIDGenerator_NewV4_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUUIDGenerator_NewV4_Call) RunAndReturn(run func() (uuid.UUID, error)) *MockUUIDGenerator_NewV4_Call {
	_c.Call.Return(run)
	return _c
}

// NewV7 provides a mock function for the type MockUUIDGenerator
func (_mock *MockUUIDGenerator) NewV7() (uuid.UUID, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewV7")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uuid.UUID, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUUIDGenerator_NewV7_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewV7'
type MockUUIDGenerator_NewV7_Call struct {
	*mock.Call
}

// NewV7 is a helper method to define mock.On call
func (_e *MockUUIDGenerator_Expecter) NewV7() *MockUUIDGenerator_NewV7_Call {
	return &MockUUIDGenerator_NewV7_Call{Call: _e.mock.On("NewV7")}
}

func (_c *MockUUIDGenerator_NewV7_Call) Run(run func()) *MockUUIDGenerator_NewV7_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUUIDGenerator_NewV7_Call) Return(uUID uuid.UUID, err error) *MockUUIDGenerator_NewV7_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUUIDGenerator_NewV7_Call) RunAndReturn(run func() (uuid.UUID, error)) *MockUUIDGenerator_NewV7_Call {
	_c.Call.Return(run)
	return _c
}
