---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  size:
    name: Size
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      pull-requests: write # for adding labels to PRs
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Size
        id: size
        uses: mattdowdell/pr-sizer@ee8ce3fa199d4fb213b010253e362216d26463c4 # v0.5.2

      - name: Outputs
        run: |
          echo "size=${SIZE}"
          echo "includes=${INCLUDES}"
          echo "excludes=${EXCLUDES}"
          echo "ignores=${IGNORES}"
        env:
          SIZE: ${{ steps.size.outputs.size }}
          INCLUDES: ${{ steps.size.outputs.includes }}
          EXCLUDES: ${{ steps.size.outputs.excludes }}
          IGNORES: ${{ steps.size.outputs.ignores }}

  checks:
    name: Checks
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup checks
        uses: ./.github/actions/setup-checks

      - name: Start database
        uses: hoverkraft-tech/compose-action@11beaa1c2dae4e8ed7b1665aa074723b6cecb0e4 # v3.0.0
        with:
          compose-file: compose.yaml
          up-flags: --build --wait
          down-flags: --volumes --remove-orphans
          services: |
            postgres
            migrate

      - name: Seed
        run: |
          just db-seed

      - name: Checks
        run: |
          just checks dirty

  lint-go:
    name: Lint Go
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Get golangci-lint version
        id: version
        run: |
          ./tools/bingo-version.sh golangci-lint >> "$GITHUB_OUTPUT"

      - name: Lint Go
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: ${{ steps.version.outputs.version }}
          args: --timeout=10m

  lint-proto:
    name: Lint Proto
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Lint Protobuf
        uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          pr_comment: false
          format: false
          breaking: false

  lint-actions:
    name: Lint Actions
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Lint Actions
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          fail_level: any

  link-k8s:
    name: Lint K8S
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Install Just
        uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with:
          tool: just

      - name: Install bingo
        uses: mattdowdell/go-installer@de5d072ade9fc895652cd6a93ac4bde11e105bc6 # v0.4.0
        with:
          package: github.com/bwplotka/bingo

      - name: Lint K8S
        run: |
          just lint-k8s

  unit:
    name: Unit test
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Install Just
        uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with:
          tool: just

      - name: Unit test
        run: just unit

    # TODO: report coverage to PR
    # maybe gwatts/go-coverage-action?

  scan-trivy:
    name: Scan Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      # required for trivy to find licenses
      # see https://trivy.dev/latest/docs/coverage/language/golang/#license
      - name: Populate Go mod cache
        run: go mod tidy

      - name: Get trivy version
        id: trivy-version
        run: |
          ./tools/bingo-version.sh trivy >> "$GITHUB_OUTPUT"

      - name: Run trivy
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: fs
          trivy-config: trivy.yaml
          format: sarif
          output: trivy-results.sarif
          version: ${{ steps.trivy-version.outputs.version }}

      # TODO: always run
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: trivy-results.sarif

  scan-zizmor:
    name: Scan Zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          persona: pedantic

  scan-gitleaks:
    name: Scan Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run gitleaks
        uses: ./.github/actions/gitleaks

      # TODO: always run
      - name: Upload Gitleaks scan results
        uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: gitleaks.sarif

  functional-compose:
    name: Functional Tests (Compose)
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Just
        uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with:
          tool: just

      - name: Enable coverage
        run: |
          # hack to let container's user create coverage files
          sudo chown 65532:65532 .covdata

          # enable coverage builds
          echo "GO_BUILD_ARGS=-cover -covermode=atomic" > .env

      - name: Start
        uses: hoverkraft-tech/compose-action@11beaa1c2dae4e8ed7b1665aa074723b6cecb0e4 # v3.0.0
        with:
          compose-file: compose.yaml
          up-flags: --build --wait
          down-flags: --volumes --remove-orphans

      - name: Functional test
        run: just functional

      - name: Collect coverage
        run: |
          curl -X POST http://localhost:5000/coverage -v

          # TODO: publish this somewhere
          go tool covdata percent -i=.covdata
          go tool covdata textfmt -i=.covdata -o cover.out

          go run ./tools/filter-coverage/ -output=functional.out cover.out
          echo "Total coverage: $(go tool cover -func=functional.out | tail -n 1 | awk '{print $3}')"

      - name: Collect logs
        if: always()
        run: |
          echo "::group::rpc logs"
          docker compose logs rpc
          echo "::endgroup::"

          echo "::group::migrate logs"
          docker compose logs migrate
          echo "::endgroup::"

          echo "::group::postgres logs"
          docker compose logs postgres
          echo "::endgroup::"

  functional-tilt:
    name: Functional Tests (Tilt)
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: "go.mod"

      - name: Install Just
        uses: taiki-e/install-action@9bcaee1dcae34154180f412e2fa69355a7cda9f6 # v2.82.6
        with:
          tool: just

      - name: Install bingo
        uses: mattdowdell/go-installer@de5d072ade9fc895652cd6a93ac4bde11e105bc6 # v0.4.0
        with:
          package: github.com/bwplotka/bingo

      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
          mkdir -p "$HOME/.local/bin/"
          install -m 0755 kubectl "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install Tilt
        run: |
          gh release download --repo tilt-dev/tilt v0.37.0 --pattern '*.linux.x86_64.tar.gz'
          tar -xvzf ./*.linux.x86_64.tar.gz tilt
          mkdir -p "$HOME/.local/bin/"
          install -m 0755 tilt "$HOME/.local/bin/"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup
        run: |
          just kind-up
          tilt ci
        env:
          # enable coverage builds
          GO_BUILD_ARGS: "-cover -covermode=atomic"

      - name: Pre-test check
        run: |
          kubectl get deployments
          kubectl get pods

      - name: Port-forward
        run: |
          kubectl port-forward svc/example-rpc 5000:5000 &

      - name: Test
        run: just functional

      # TODO: look into fixing this
      # - name: Collect coverage
      #   run: |
      #     set -x
      #     i=0
      #     for name in $(kubectl get po -lapp=example -ojsonpath='{.items[*].metadata.name}'); do
      #       kubectl port-forward "pod/$name" "600$i:5000" &
      #       sleep 3
      #       curl -X POST "http://localhost:600$i/coverage" -v
      #       kubectl cp ./.covdata/ "$name:/covdata/*"
      #       kill %1
      #       ((i++))
      #     done

      #     ls -alph ./.covdata/

      #     go tool covdata percent -i=.covdata
      #     go tool covdata textfmt -i=.covdata -o cover.out

      #     go run ./tools/filter-coverage/ -output=functional.out cover.out
      #     echo "Total coverage: $(go tool cover -func=functional.out | tail -n 1 | awk '{print $3}')"

      - name: Collect logs
        if: always()
        run: |
          for name in $(kubectl get po -lapp=example -ojsonpath='{.items[*].metadata.name}'); do
            echo "::group::kubectl logs $name"
            kubectl logs "$name"
            echo "::endgroup::"
          done

          echo "::group::kubectl logs example-db-migrate"
          kubectl logs -lbatch.kubernetes.io/job-name=example-db-migrate
          echo "::endgroup::"

  version:
    name: Version
    needs:
      - unit
      - scan-gitleaks
      - scan-trivy
      - scan-zizmor
      - functional-compose
      - functional-tilt
    permissions:
      contents: write # for pushing tags (and checkout)
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Version
        id: version
        uses: ./.github/actions/zerover
        with:
          create: ${{ github.event_name == 'push' }}

  build:
    name: Build
    needs:
      - version
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      packages: write # for container push
      id-token: write # for keyless image signing
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: GHCR Login
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Setup cosign
        uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Get trivy version
        id: trivy-version
        run: |
          ./tools/bingo-version.sh trivy >> "$GITHUB_OUTPUT"

      - name: Build
        uses: ./.github/actions/container-build
        with:
          service: example-rpc
          repository: ghcr.io/mattdowdell/sandbox/example-rpc
          version: ${{ needs.version.outputs.version }}
          trivy-version: ${{ steps.trivy-version.outputs.version }}
