name: CI

on:
  pull_request:

jobs:
  size:
    name: Size
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Size
        uses: mattdowdell/pr-size@main

  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install Buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install gci
        uses: ./.github/actions/go-install
        with:
          package: github.com/daixiang0/gci
          name: gci

      - name: Install gofumpt
        uses: ./.github/actions/go-install
        with:
          package: mvdan.cc/gofumpt
          name: gofumpt

      # - name: Install mockery
      #   uses: ./.github/actions/go-install
      #   with:
      #     package: github.com/vektra/mockery/v2
      #     name: mockery

      - name: Install wire
        uses: ./.github/actions/go-install
        with:
          package: github.com/google/wire/cmd/wire
          name: wire

      - name: Checks
        run: just checks

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
          uses: actions/setup-go@v4
          with:
            go-version-file: 'go.mod'

      - name: Lint Go
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'latest'

      - name: Lint Protobuf
        uses: bufbuild/buf-action@v1
        with:
          pr_comment: false
          # input:
          format: false
          breaking: false

  unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Unit test
        run: just unit
