name: CI

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # TODO: limit to pull requests, don't kill branch builds

jobs:
  size:
    name: Size
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Size
        id: size
        uses: mattdowdell/pr-sizer@45266d54471a64e7698eac319d2ee8b6cb13cc3d # v0.1.0

      - name: Outputs
        run: |
          echo size=${SIZE}
          echo includes=${INCLUDES}
          echo excludes=${EXCLUDES}
        env:
          SIZE: ${{ steps.size.outputs.size }}
          INCLUDES: ${{ steps.size.outputs.includes }}
          EXCLUDES: ${{ steps.size.outputs.excludes }}

  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup checks
        uses: ./.github/actions/setup-checks

      - name: Checks
        run: |
          just checks dirty

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Lint Go
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
          args: --timeout=10m

      - name: Lint Protobuf
        uses: bufbuild/buf-action@v1
        with:
          pr_comment: false
          format: false
          breaking: false

  unit:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Unit test
        run: just unit

      # TODO: report coverage to PR
      # maybe gwatts/go-coverage-action?

  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run scanner
        uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0
        with:
          scan-type: fs
          trivy-config: trivy.yaml

      # TODO: publish to github for default branch builds
      # https://github.com/actions/starter-workflows/blob/main/code-scanning/trivy.yml
