---
name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  size:
    name: Size
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      pull-requests: write # for adding labels to PRs
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Size
        id: size
        uses: mattdowdell/pr-sizer@0dae752c3a2a3bbba738230d857a303a3798cf6e # v0.5.1

      - name: Outputs
        run: |
          echo size=${SIZE}
          echo includes=${INCLUDES}
          echo excludes=${EXCLUDES}
          echo ignores=${IGNORES}
        env:
          SIZE: ${{ steps.size.outputs.size }}
          INCLUDES: ${{ steps.size.outputs.includes }}
          EXCLUDES: ${{ steps.size.outputs.excludes }}
          IGNORES: ${{ steps.size.outputs.ignores }}

  checks:
    name: Checks
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup checks
        uses: ./.github/actions/setup-checks

      - name: Start database
        uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3 # v2.5.0
        with:
          compose-file: compose.yaml
          up-flags: --build --wait
          down-flags: --volumes --remove-orphans
          services: |
            postgres
            migrate

      - name: Seed
        run: |
          just db-seed

      - name: Checks
        run: |
          just checks dirty

  lint:
    name: Lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"

      - name: Get version
        id: version
        run: |
          ./tools/bingo-version.sh golangci-lint >> $GITHUB_OUTPUT

      - name: Lint Go
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: ${{ steps.version.outputs.version }}
          args: --timeout=10m

      - name: Lint Protobuf
        uses: bufbuild/buf-action@8f4a1456a0ab6a1eb80ba68e53832e6fcfacc16c # v1.3.0
        with:
          pr_comment: false
          format: false
          breaking: false

  unit:
    name: Unit test
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"

      - name: Install Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Unit test
        run: just unit

    # TODO: report coverage to PR
    # maybe gwatts/go-coverage-action?

  scan:
    name: Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"

      - name: Install Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      # required for trivy to find licenses
      # see https://trivy.dev/latest/docs/coverage/language/golang/#license
      - name: Populate Go mod cache
        run: just tidy-go

      - name: Get trivy version
        id: trivy-version
        run: |
          ./tools/bingo-version.sh trivy >> $GITHUB_OUTPUT

      - name: Run trivy
        uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518 # 0.34.1
        with:
          scan-type: fs
          trivy-config: trivy.yaml
          format: sarif
          output: trivy-results.sarif
          version: ${{ steps.trivy-version.outputs.version }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@89a39a4e59826350b863aa6b6252a07ad50cf83e # v4.32.4
        with:
          sarif_file: trivy-results.sarif

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          persona: pedantic

      - name: Run gitleaks
        uses: ./.github/actions/gitleaks

  functional:
    name: Functional Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3.1.0

      - name: Setup coverage
        uses: gacts/run-and-post-run@81b6ce503cde93862cec047c54652e45c5dca991 # v1.4.3
        with:
          run: |
            # hack to let container's user create coverage files
            sudo chown 65532:65532 .covdata

            # enable coverage builds
            echo GO_BUILD_ARGS=-cover > .env
          post: |
            # TODO: publish this somewhere
            go tool covdata percent -i=.covdata

            go tool covdata textfmt -i=.covdata -o cover.out
            go run ./tools/filter-coverage/ -output=functional.out cover.out
            echo "Total coverage: `go tool cover -func=functional.out | tail -n 1 | awk '{print $3}'`"

      - name: Start
        uses: hoverkraft-tech/compose-action@4894d2492015c1774ee5a13a95b1072093087ec3 # v2.5.0
        with:
          compose-file: compose.yaml
          up-flags: --build --wait
          down-flags: --volumes --remove-orphans

      - name: Functional test
        run: just functional

      - name: Collect logs
        if: always()
        run: |
          echo "::group::rpc logs"
          docker compose logs rpc
          echo "::endgroup::"

          echo "::group::migrate logs"
          docker compose logs migrate
          echo "::endgroup::"

          echo "::group::postgres logs"
          docker compose logs postgres
          echo "::endgroup::"

  tag:
    name: Tag
    needs:
      - unit
      - scan
      - functional
    permissions:
      contents: write # for pushing tags (and checkout)
    runs-on: ubuntu-latest
    outputs:
      short: ${{ steps.tag.outputs.short }}
      long: ${{ steps.tag.outputs.long }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Tag
        id: tag
        uses: ./.github/actions/tag
        with:
          rollover: true

  build:
    name: Build
    needs:
      - tag
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout
      packages: write # for container push
      id-token: write # for keyless image signing
      security-events: write # for uploading code scanning results
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: GHCR Login
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Setup cosign
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0

      - name: Get trivy version
        id: trivy-version
        run: |
          ./tools/bingo-version.sh trivy >> $GITHUB_OUTPUT

      - name: Build
        uses: ./.github/actions/container-build
        with:
          service: example-rpc
          repository: ghcr.io/mattdowdell/sandbox/example-rpc
          version: ${{ needs.tag.outputs.long }}
          trivy-version: ${{ steps.trivy-version.outputs.version }}
