name: Regenerate

on:
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  debug:
    regenerate: Regenerate
    permissions:
      contents: read # TODO: update to write
      pull-requests: read # TODO: update to write?
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regenerate') }}
    steps:
      - name: Debug
        run: |
          cat << 'EOF'
          ${{ toJSON(github) }}
          EOF

      - name: Acknowledge
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/${{  }}/reactions -f "content=$2

          gh api
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer <YOUR-TOKEN>" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f "content=+1" || true

      - name: PR HEAD reference
        id: ref
        run: |
          echo "ref=`gh pr view '${{ github.event.issue.number }}' \
            --repo ${{ github.repository }} \
            --template '{{ .headRefName }}' \
            --json headRefName`" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}

  # regenerate:
  #   name: Regenerate
  #   runs-on: ubuntu-latest
  #   if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regenerate') }}
  #   steps:
  #     # TODO: add :+1: reaction to acknowledge regenerate comment
  #     # https://github.com/cli/cli/issues/6161#issuecomment-2650577115

  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.head_ref }}

  #     - name: Install Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version-file: 'go.mod'

  #     - name: Install Buf
  #       uses: bufbuild/buf-action@v1
  #       with:
  #         setup_only: true

  #     - name: Install Just
  #       uses: extractions/setup-just@v2

  #     - name: Install gci
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: github.com/daixiang0/gci
  #         version-file: go.mod

  #     - name: Install gofumpt
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: mvdan.cc/gofumpt
  #         version-file: go.mod

  #     - name: Install mockery
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: github.com/vektra/mockery/v2
  #         version-file: go.mod

  #     - name: Install protoc-gen-connect-go
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: connectrpc.com/connect/cmd/protoc-gen-connect-go
  #         version-file: go.mod

  #     - name: Install protoc-gen-go
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: google.golang.org/protobuf/cmd/protoc-gen-go
  #         version-file: go.mod

  #     - name: Install wire
  #       uses: mattdowdell/go-installer@v0.2.0
  #       with:
  #         package: github.com/google/wire/cmd/wire
  #         version-file: go.mod

  #     - name: Regenerate
  #       run: |
  #         just checks

  #     - name: Commit diff
  #       run: |
  #         git config user.name "github-actions[bot]"
  #         git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

  #         git status
  #         git diff

  #         git add .
  #         # git commit -m "Regenerate code"
  #         # git push

