name: Regenerate

on:
  issue_comment:
    types:
      - created
      - edited

jobs:
  regenerate:
    name: Regenerate
    permissions:
      contents: write      # for pushing updates after regenerating
      pull-requests: write # for obtaining head ref + reaction acknowledgement
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regenerate') }}
    steps:
      - name: Acknowledge
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f "content=+1"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: PR branch
        id: ref
        run: |
          echo "ref=`gh pr view '${{ github.event.issue.number }}' \
            --repo ${{ github.repository }} \
            --template '{{ .headRefName }}' \
            --json headRefName`" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - name: Setup checks
        uses: ./.github/actions/setup-checks

      - name: Regenerate
        run: |
          just checks

      - name: Commit diff
        run: |
          if git diff --quiet -- .
          then
            echo "regenerate found no changes"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Regenerate code"
          git push
