name: Regenerate

on:
  issue_comment:
    types:
      - created
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  regenerate:
    name: Regenerate
    permissions:
      contents: read # TODO: update to write
      pull-requests: write # TODO: update to write?
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/regenerate') }}
    steps:
      - name: Debug
        run: |
          cat << 'EOF'
          ${{ toJSON(github) }}
          EOF

      - name: Acknowledge
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions \
            -f "content=+1" || true
        env:
          GH_TOKEN: ${{ github.token }}

      - name: PR HEAD reference
        id: ref
        run: |
          echo "ref=`gh pr view '${{ github.event.issue.number }}' \
            --repo ${{ github.repository }} \
            --template '{{ .headRefName }}' \
            --json headRefName`" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.ref }}

      - name: Install tools
        uses: ./.github/actions/setup-checks

      - name: Regenerate
        run: |
          just checks

      - name: Commit diff
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git status
          git diff

          git add .
          # git commit -m "Regenerate code"
          # git push

