// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/mattdowdell/sandbox/internal/drivers/config"
	"github.com/mattdowdell/sandbox/internal/drivers/config/flagoptions"
	"github.com/mattdowdell/sandbox/internal/drivers/logging"
	"github.com/mattdowdell/sandbox/internal/drivers/otelx"
	"github.com/mattdowdell/sandbox/internal/drivers/pgsql"
)

// Injectors from wire.go:

func ProvideApp(ctx context.Context) (*App, error) {
	options := flagoptions.New()
	configConfig := config.New(options)
	mainConfig, err := LoadConfig(configConfig)
	if err != nil {
		return nil, err
	}
	loggingConfig := mainConfig.Logging
	v := loggerOptions()
	logger := logging.NewAsDefaultFromConfig(loggingConfig, v...)
	pgsqlConfig := mainConfig.Database
	db, err := pgsql.NewFromConfig(ctx, pgsqlConfig)
	if err != nil {
		return nil, err
	}
	tracerProviderConfig := mainConfig.TracerProvider
	filter := baggageFilter()
	tracerProviderShutdown, err := otelx.SetupTracerProviderFromConfig(ctx, tracerProviderConfig, filter)
	if err != nil {
		return nil, err
	}
	meterProviderConfig := mainConfig.MeterProvider
	meterProviderShutdown, err := otelx.SetupMeterProviderFromConfig(ctx, meterProviderConfig)
	if err != nil {
		return nil, err
	}
	loggerProviderConfig := mainConfig.LoggerProvider
	loggerProviderShutdown, err := otelx.SetupLoggerProviderFromConfig(ctx, loggerProviderConfig, filter)
	if err != nil {
		return nil, err
	}
	app := NewApp(mainConfig, logger, db, tracerProviderShutdown, meterProviderShutdown, loggerProviderShutdown)
	return app, nil
}
