{{- range $name, $configmap := .Values.configmaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  labels:
    {{- include "helper.labels" $ | nindent 4 }}
data:
  {{- with $configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
