---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helper.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "helper.fullname" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ include "helper.fullname" . }}
    helm.sh/chart: {{ include "helper.chart" . }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
