{{- range $i, $job := .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    app.kubernetes.io/part-of: {{ $.Chart.Name }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: {{ .name }}
        app.kubernetes.io/name: {{ .name }}
        app.kubernetes.io/version: {{ $.Chart.AppVersion }}
        app.kubernetes.io/part-of: {{ $.Chart.Name }}
    spec:
      containers:
        {{- range .containers }}
        - name: {{ .name }}
          image: {{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}
          imagePullPolicy: {{ .image.pullPolicy | default "Always" }}
          command: ["/{{ .name }}"]
          securityContext: {{- toYaml $.Values.securityContext | nindent 12 }}
          {{- if .env }}
          env:
            {{- range $name, $value := .env }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end}}
          {{- end }}
          {{- if or $job.configmaps $job.secrets }}
          volumeMounts:
            {{- range $job.configmaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
            {{- range $job.secrets }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: true
            {{- end }}
          {{- end }}
        {{- end }}
      {{- if or $job.configmaps $job.secrets }}
      volumes:
        {{- range .configmaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
        {{- range .secrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            {{- if .items }}
            items:
              {{- range .items }}
              - key: {{ .key }}
                {{- if .path }}
                path: {{ .path }}
                {{- end }}
              {{- end }}
            {{- end }}
        {{- end }}
      {{- end }}
      restartPolicy: Never
{{- end }}
