// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package rpcserver

import (
	"net/http"

	"connectrpc.com/connect"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockHandler
func (_mock *MockHandler) Register(serveMux *http.ServeMux, handlerOptions []connect.HandlerOption) {
	_mock.Called(serveMux, handlerOptions)
	return
}

// MockHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - serveMux *http.ServeMux
//   - handlerOptions []connect.HandlerOption
func (_e *MockHandler_Expecter) Register(serveMux any, handlerOptions any) *MockHandler_Register_Call {
	return &MockHandler_Register_Call{Call: _e.mock.On("Register", serveMux, handlerOptions)}
}

func (_c *MockHandler_Register_Call) Run(run func(serveMux *http.ServeMux, handlerOptions []connect.HandlerOption)) *MockHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *http.ServeMux
		if args[0] != nil {
			arg0 = args[0].(*http.ServeMux)
		}
		var arg1 []connect.HandlerOption
		if args[1] != nil {
			arg1 = args[1].([]connect.HandlerOption)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Register_Call) Return() *MockHandler_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_Register_Call) RunAndReturn(run func(serveMux *http.ServeMux, handlerOptions []connect.HandlerOption)) *MockHandler_Register_Call {
	_c.Run(run)
	return _c
}
