---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example
data:
  authn_address: "http://localhost:5000"
  database_hostname: "postgresql-cluster-rw.default.svc.cluster.local"
  database_sslmode: "disable"
  issuer_audience: "example"
  issuer_issuer: "example"
  loggerprovider_endpoint: "victoria-logs-victoria-logs-single-server.observability.svc.cluster.local:9428"
  loggerprovider_insecure: "true"
  loggerprovider_path: "/insert/opentelemetry/v1/logs"
  logging_level: "debug"
  meterprovider_endpoint: "victoria-metrics-victoria-metrics-single-server.observability.svc.cluster.local:8428"
  meterprovider_insecure: "true"
  meterprovider_path: "/opentelemetry/v1/metrics"
  parser_audience: "example"
  parser_issuer: "example"
  parser_methods: "HS256"
  rpcserver_host: "0.0.0.0"
  rpcserver_enablecoverage: "true"
  rpcserver_enablepprof: "true"
  tracerprovider_insecure: "true"
  tracerprovider_endpoint: "victoria-traces-vt-single-server.observability.svc.cluster.local:10428"
  tracerprovider_path: "/insert/opentelemetry/v1/traces"
